This notebook will load three different classifiers to label tweets hierarchically at 3 different levels. First, they will be sorted into behavior-related vs. not related. Second, they will be classified into 1st person vs. not 1st person. Third, a label will be assigned to first-person, behavior-related tweets that show time-related activity in the past, present, or future. 

First, we load the requisite modules into the environmment and change our base directory.

In [1]:
# ! pip install pbs
# import pbs
# print(pbs.__version__)
print()
# ! pip install pipelines

In [2]:
import os
import pickle
# import sklearn
# !pip install --upgrade pip
# !dir
# !pip install --upgrade sklearn
import sklearn
print(sklearn.__version__)
import pandas
import numpy
import sys
# import pipelines
# from sklearn.pipeline import FeatureUnion, Pipeline
# sys.modules['pipelines'] = Pipeline

0.21.1


In [3]:
# os.chdir('/Users/dethf/NYU/Spring 2019/Chunara Internship/nyu-twipsy/')
print(os.path.abspath(os.curdir))
os.chdir(os.path.abspath(os.curdir))
# os.chdir(sys.path[0])

C:\Users\eddie\Desktop\Rumi\alcohol


Next, we load the pickle files which contain our classifiers. 

In [4]:
# clf_alc    = pickle.load(open('/Users/dethf/NYU/Spring 2019/Chunara Internship/nyu-research/notebooks/python/classifiers/clf_alc_UPDATED.p', 'rb'))
# clf_fpa    = pickle.load(open('/Users/dethf/NYU/Spring 2019/Chunara Internship/nyu-research/notebooks/python/classifiers/clf_fpa_UPDATED.p', 'rb'))
# clf_fpl_dl = pickle.load(open('/Users/dethf/NYU/Spring 2019/Chunara Internship/nyu-research/notebooks/python/classifiers/clf_fpl_double_labeled', 'rb'))

# clf_fpa    = pickle.load(open('tobacco classifiers/clf_fpa_UPDATED.p', 'rb'))
clf_alc    = pickle.load(open('./alcohol classifiers/clf_alc_UPDATED.p', 'rb'))
clf_fpa    = pickle.load(open('./alcohol classifiers/clf_fpa_UPDATED.p', 'rb'))
clf_fpl_dl = pickle.load(open('./alcohol classifiers/clf_fpl_double_labeled', 'rb'))


C:\Users\eddie\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:306: UserWarning: Trying to unpickle estimator TfidfTransformer from version pre-0.18 when using version 0.21.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\eddie\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:306: UserWarning: Trying to unpickle estimator TfidfVectorizer from version pre-0.18 when using version 0.21.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\eddie\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:306: UserWarning: Trying to unpickle estimator Pipeline from version pre-0.18 when using version 0.21.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\eddie\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:306: UserWarning: Trying to unpickle estimator FeatureUnion from version pre-0.18 when using

In [5]:
# set the threshold: 99% of data is not alcohol related
#! jonathan comment: not really sure what this does. 
#! I know it's related to the 1% of tweets related to alcohol, but not much else. 
#clf_alc.steps[2][1].class_weight = {0:0.99, 1:0.01}
#clf_fpa.steps[2][1].class_weight = {0:0.5, 1:0.5}
#clf_fpl_dl.steps[2][1].class_weight = {0:0.99, 1:0.01}

Here we will use some pre-classified tweets and regenerate the alcohol-related vs. not alcohol-related, first-person vs. not first-person, and first-person-level labels. Since the data were used to train the classifier initially and were hand-annotated by MTurk workers, We should not expect to come up with identical labels for these levels of classification.

In [6]:
df = pandas.read_csv("./data/alcohol_training_instances.csv")

In [39]:
# printing the first 5 tweets to check content
df.text[0:5]

0    Impatiently waiting to get our hands on the ne...
1    Beer fans need their @ColumbusBrewing Bodhi. I...
2    Beer Olympics with my #1 fan and babe😍❤️ #Team...
3    Stone Cold use to be the baddest MF in my book...
4    Now @iamjohnoliver has to drink a Bud Light Li...
Name: text, dtype: object

In [42]:
%%time
## running the classifiers
# alcohol vs. not alcohol related
pred_alc= clf_alc.predict(df)
print(len(pred_alc))

# first-person vs. not first-person
#pred_alc_fp = clf_fpa.predict(df)

# first person level
#pred_fpl_dl = clf_fpl_dl.predict(df)

15651
Wall time: 4.2 s


We now check to see how well our classifier did reproducing the same labels as the pre-classified tweets.

In [52]:
alc_labels = []
# extracting pre-labeled classification
for i in range(0,len(df.labels)):
    alc_labels.append(df.labels[i][12])
# print(alc_labels[:10])

alc_labels = list(map(int, alc_labels))

# testing to see if the classifier generated the same labels    
comps = alc_labels != pred_alc
# print(len(comps))
comps = list(numpy.where(comps)[0])
print(comps)
print('pretrained alcohol classifer:  %d different item in whole dataset'%(len(comps)))

[2554, 2750, 7824, 9284, 9938, 11069, 12959, 13600]
pretrained alcohol classifer:  8 different item in whole dataset


Next we check to see what mismatched tweets there are and their content. 

In [53]:
# printing the mismatched labels and tweets
for i in comps:
    print('index %d'%(i))
    print(df.text[i], '\n', 'original label:', alc_labels[i], 'prediction:', pred_alc[i], '\n \n')

index 2554
Purple Wedding Drank
#GameOfThronesFood @midnight 
 original label: 1 prediction: 0 
 

index 2750
I'm a little drunk on you and high on summertime 
 original label: 1 prediction: 0 
 

index 7824
❤️😜
Drinking 
 original label: 0 prediction: 1 
 

index 9284
BEST #ATLANTA #REAL #ESTATE
#Chateau #Elan #Winery #Resort #GA 
2 Ac  ESTATE
info@cbmsinc.com 
http://t.co/Rl5gNnIeZl http://t.co/R1NwrUGTcO 
 original label: 1 prediction: 0 
 

index 9938
My #TeenChoice nominee for #ChoiceMaleWebStar is @TheMattEspinosa http://t.co/igxiscmsLY x1.017 
 original label: 1 prediction: 0 
 

index 11069
&lt;Creedy&gt; fucking jesus
&lt;Creedy&gt; i have to kill that bitch
&lt;logicalentity&gt; jesus?
&lt;logicalentity&gt; the romans beat ya 
 original label: 1 prediction: 0 
 

index 12959
It's better to love and then lost than to never have loved at all
If that was true I wouldn't be drinking this alcohol 🎶 
 original label: 0 prediction: 1 
 

index 13600
@NiallOfficial The show in Brusse

We see that there are 8 mismatched tweets. It seems remarkably accurate in reproducing the same labels as the human-annotated ones. 

We can check a different way to see if the classification was agreement with the original labels by subsetting the original labeled dataset by the predictions. We should see only tweets starting with the 'alcohol': 1 label, for the most part. 

In [60]:
# actually don't get it. it seems subset doesnt subsetting the original labeled dataset by the predictions
# subset = list(map(bool, pred_alc))
# print(len(subset))
# print(subset[:14])
# print(pred_alc[:14])
# df.iloc[subset,].labels[0:14]
# df.iloc[subset,][:14]

It looks like this initial classification was successful. 

Here we will subset our dataframe to only include alcohol-related tweets but also exclude tweets with having solely the "'alcohol': 1" label. We will then extract the first-person labels.

In [61]:
print(df.labels[:15])
subset_vec_alc_fp = []
for i in range(len(df)):
    if "'alcohol': 1" and "'first_person': 1" in df.labels[i]:
        subset_vec_alc_fp.append(1) 
    elif "'alcohol': 1" and "'first_person': 0" in df.labels[i]:
        subset_vec_alc_fp.append(1)
    else:
        subset_vec_alc_fp.append(0)

0                                        {'alcohol': 0}
1     {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
2     {'alcohol': 1, 'first_person_level': 0, 'first...
3     {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
4     {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
5     {'alcohol': 1, 'first_person_level': 0, 'first...
6     {'alcohol': 1, 'first_person_level': 2, 'first...
7     {'alcohol': 1, 'first_person_level': 2, 'first...
8                                        {'alcohol': 0}
9     {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
10                                       {'alcohol': 0}
11    {'alcohol': 1, 'first_person_level': 1, 'first...
12    {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
13    {'alcohol': 1, 'first_person_level': 0, 'first...
14    {'alcohol': 1, 'first_person': 0, 'alcohol_rel...
Name: labels, dtype: object


In [68]:
# this shows how many tweets had the first-person classifier run on them.
sum(subset_vec_alc_fp)
# print(len(subset_vec_alc_fp))

9816

We will now extract the first-person labels from each of the original alcohol-related training tweets.

In [69]:
fp_lab = []

fp_0 = "'first_person': 0"
fp_1 = "'first_person': 1"

# the actual extraction
for i in range(len(df)):
    if fp_0 in df.labels[i] or fp_1 in df.labels[i]:
        if df.labels[i].find(fp_0) != -1:
            fp_lab.append(df.labels[i][df.labels[i].find(fp_0) + len(fp_0) - 1])
        else:
            fp_lab.append(df.labels[i][df.labels[i].find(fp_1) + len(fp_0) - 1])
print(fp_lab[:50])
# print(subset_vec_alc_fp[:10])
print(len(fp_lab))

['0', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0', '1', '1', '1', '1', '1', '1']
9816


Having extracted the original labels, we will now run the first-person classifier only on the tweets that were labeled originally. The classifier will not be run on tweets with solely the 'alcohol': 1 label. 

In [73]:
%%time
subset_vector = list(numpy.where(subset_vec_alc_fp)[0])
print(subset_vector[:10])
print(len(subset_vector)) # 9816

# print(df.iloc[subset_vector,][:10])
alc_fp_preds = clf_fpa.predict(df.iloc[subset_vector,])

[1, 2, 3, 4, 5, 6, 7, 9, 11, 12]
Wall time: 1min 29s


In [76]:
print(len(alc_fp_preds))
print(alc_fp_preds[:10])

9816
[1 1 1 1 1 1 1 1 1 1]


In [16]:
%%time
# array of probabilities
alc_fp_probs = clf_fpa.predict_proba(df[numpy.array(subset_vec_alc_fp) == 1])

In [74]:
print(len(alc_fp_probs))
print(alc_fp_probs[:10])

9816
[[0.4863973  0.5136027 ]
 [0.38392558 0.61607442]
 [0.47635895 0.52364105]
 [0.5        0.5       ]
 [0.16786706 0.83213294]
 [0.17335971 0.82664029]
 [0.14116919 0.85883081]
 [0.3576541  0.6423459 ]
 [0.11937854 0.88062146]
 [0.56474672 0.43525328]]


Here we will compare the original labels we extracted to the classifier's predictions. We will check to see what the rate of agreement is between our newly-generated predictions and the original annotations (labels).

In [17]:
fp_lab = list(map(int, fp_lab))
disag = alc_fp_preds != fp_lab
1-sum(disag)/len(disag)
#disag_subset = list(map(bool, disag))

#disag_idx = df.iloc[subset_vector,].iloc[disag_subset,].index.tolist()

#for i in disag_idx:
#    print(df.text[i], "\n original label:", fp_lab[i],"\n prediction:", alc_fp_preds[i], "\n\n")

0.7512224938875306

Our rate of agreement is about 75%. We now look at the tweet content as well as the original labels, the predictions, and the probabilities.

In [18]:
alc_fp_tweets = df[numpy.array(subset_vec_alc_fp) == 1].text
alc_fp_probs_round = numpy.around(alc_fp_probs,2).tolist()

for tweet, label, pred, prob in zip(alc_fp_tweets, fp_lab, alc_fp_preds, alc_fp_probs_round):
    print(tweet, "\n", "Original label: ", label, "Prediction: ", pred, "\n", "Probabilies: ", prob, "\n\n")

Beer fans need their @ColumbusBrewing Bodhi. I'm making another @tdg_powell trip for the #MemorialTournament http://t.co/Z9u3NrCBea 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.49, 0.51] 


Beer Olympics with my #1 fan and babe😍❤️ #TeamJamaica http://t.co/2hAT4vDQUT 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


Stone Cold use to be the baddest MF in my book lol dude use to get hype; whip your ass and waste a case of beer in the ring 😂 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.48, 0.52] 


Now @iamjohnoliver has to drink a Bud Light Lime #SeppBlatter 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Drinking a Soft Parade by @ShortsBrewing @ Lake Johnson — http://t.co/XedrcSi9SS 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Its only Tuesday and I need a drink or four. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


jess told me no puking this friday.. so that means no getting drunk... 

 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


You will never hear me say i want a one/small glass of wine, just being honest. 🍷#ilovewine 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.45, 0.55] 


If my wife's hobbies don't include drinking beer and watching hockey while complaining about our friends who don't drink, it won't last 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.52, 0.48] 


Why why would Princess tag me in a drunk photo on Facebook I'm crying 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


Drinking a Nut Brown Ale by @peakbrewing @ Berkeley Trace Apartments — http://t.co/QLMzDfCNPD 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


Drinking a Belmont Abbey Robust Porter by @highlandbrews at @ncbeertemple — http://t.co/7HcUacuRdo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Drinking a Citra Session IPA by @GreenFlashBeer at @starsrooftop — http://t.co/u5voxP40Yc 
 Original label

 Original label:  1 Prediction:  1 
 Probabilies:  [0.45, 0.55] 


Storm King and The Match Game my life rocks - Drinking a Storm King by @VictoryBeer @ Holiday Cafe  — http://t.co/9lHaJsqzMl 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.11, 0.89] 


I love beer, beer loves me. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


I know you've been drinking but I still need your ID. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.3, 0.7] 


Drunk off sleepy time tea 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


About to go to this lil bbq and have a couple drinks I guess 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.1, 0.9] 


Drinking a Resurrection by @brewersart at @percystreet — http://t.co/DmNkRTDniB 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Shout out to @BradWIlhelm515 for giving me back alley Mother Bears so I can drink longer tonight. YOU DA BES, AND YOU HAVE MY VOTE FOR MAYOR 
 Original label

 Original label:  0 Prediction:  1 
 Probabilies:  [0.49, 0.51] 


Just added Wild Beer Somerset Saison bottles. See our full beer menu: http://t.co/vugGtql77v #BeerMenus 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.91, 0.09] 


Drinking a Bull Island by @wabashbrewing @ Wabash Brewing — http://t.co/7YLLfuEzD5 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Ice House Inn has a great selection of craft beer on tap and big glasses to drink it in. Check out the Beach @BeachShack330 out back! 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.43, 0.57] 


I really need to stop drinking ventis when i haven't eaten anything 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


All I want to do is put a drink in my hand 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.09, 0.91] 


Whatever were drinking right now got me like ayyy 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


Celebratory drinks!! @ Bakersfield Mass Ave

 Original label:  1 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


Nina so drunk she can't open the door 😂😂 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.74, 0.26] 


Drinking every night, cause we drink to my accomplishments 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


quits: ReD_JaCk (john@mask-29052.intrstar.net) (Quit: Errection killed by beer) 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.65, 0.35] 


Bittersweet kind of day, looking forward to drinking and streaming games with friends this weekend 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


So much for not drinking this month 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


hateeee waking up early after drinking 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.08, 0.92] 


Drinking a MEIYON LAGER by @Y_Market_Brew @ West Harlem Ski Area — http://t.co/Rfz9v5280F 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.27, 0.73] 


Like basicall

 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


The last thing I remember is drinking Absinthe 😂 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


Drinking a System Of A Stout by @BeachwoodBBQ_LB at @beachwoodbbq_lb — http://t.co/VEvceH2lAs #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


Drinking a Samuel Adams Boston Lager by @SamuelAdamsBeer at @outback — http://t.co/xfc1DXjruK 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking an 312 Urban Pale Ale by @GooseIsland at @hmshost — http://t.co/Uj7udEAPK0 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Drinking a Samuel Adams Summer Ale by @SamuelAdamsBeer at @unochicagogrill — http://t.co/2SjjBh43pf #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


DRINKING, chilling the weekend #Weekend #NYC #alcohol  👌👌👌 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


Drinking a Samuel Adams Imperia

 Original label:  1 Prediction:  1 
 Probabilies:  [0.14, 0.86] 


watching twilight series playing drinking games to celebrate burns 24th so maybe adulthood isn't so bad 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Nice job Italy - Drinking a Tipopils by Birrificio Italiano at @waltdisneyworld  — http://t.co/6vrXujMXtM #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


I liked this beer this kind " - matt 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


So jealous of @EthanGSN. He saw American Pharaoh cross the finish line while probably drinking whiskey and wearing a navy blazer. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.59, 0.41] 


Drinking a Hibiscus Gose by @Boulevard_Beer @ Flying Saucer Draught Emporium — http://t.co/c92tsbZ3A9 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking a Bishop's Barrel #8 by @saintarnold at @saintarnold — http://t.co/ll1rEpDzlu 
 Original label:  1 P

 Original label:  1 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


Every time I drink I end up with bruises 😑 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


I learned how to properly hold a champagne flute tonight... like it's not a beer. *pops pinky* 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.25, 0.75] 


@FlyoutChase bro I'm drunk just dying at your tweets 😂😂😂 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Drunk conversation of the night: first time sex and past relationships. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


I'm so bummed I just want to drink 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.04, 0.96] 


@franktheetank94 drunk and someone is shooting a gun or firework 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


The woman that I would try is happy with a good guy but I've been drinking so much that I'mma call her anyway and say 
 Original label:  1 Prediction:  1 
 Probab

 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Diggin the candles and wine right now 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.25, 0.75] 


7. BUT MY DRUNK ASS WAS AGGRESSIVELY AND REPEATEDLY TEXTING HIM BC I WANTED ATTENTION. So he finally tells me hes done w homework @ 10 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.31, 0.69] 


U know Gab is drunk when she comments on everyone's tweets 😂 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.81, 0.19] 


Honestly just need pizza &amp; beer or the gym rn. Maybe even both. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


I don't have a drinking problem. I just drink till I have no problems... 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.31, 0.69] 


Time to get our drank on again 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


I can't drink ALL night and be cool , but the minute I hit a blunt a couple times I'm done . That's why I can't smoke I

 Original label:  0 Prediction:  0 
 Probabilies:  [0.89, 0.11] 


Lunch beers - Drinking a Pliny the Elder by Russian River Brewing Company @ Brewco Manhattan Beach  — http://t.co/UBYGn614jy #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Drinks n then pool. Lemme know if u wanna join 😘 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


If I'm stuck with the choice of getting ahead on school work or drinking wine and playing video games the second choice always wins. Always 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.29, 0.71] 


If everyone would go out and have a drink today in my name I'd appreciate. I have finals to study for, no celebrating for me. 🎂 ➡📗📙📘📘 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


UP YOURS WISDOM TEETH! Shout out to antibiotics and beer for getting my face back to its usual size… https://t.co/xuVjDQvRVj 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.43, 0.57] 


I hate a fema

I need to lay in my bed hooked up to an IV of wine 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.11, 0.89] 


This lotion smells like beer and I just rubbed it all over myself.. Yuckkkk 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


Meh - Drinking an El Hefe Loco by @revbrewchicago at @revbrewchicago  — http://t.co/AmbVsSgKt7 #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Waking up at 6 am Saturday and popping a bottle of rum and starting the day @mariexalexandra #wedontlikesober #drunktwosome4ever 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking an Entire by Strange Land Brewery @ Whole Foods Market — http://t.co/pX9HNrGjQx 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


This weird ass shit @alexanaxx is drinking #PrayForHer http://t.co/3CxZpxM26u 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.7, 0.3] 


every time I have a really bad hangover I think "I'm never drinking aga

Drinking a Daisy Cutter Pale Ale by @halfacrebeer at @halfacrebeer — http://t.co/UuBpqsGGzf 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


I'm a little drunk on you and high on summertime 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.3, 0.7] 


Drinking a Vallejo by @halfacrebeer at @halfacrebeer — http://t.co/bl7ZZW5imy 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


Drinking a Zombie Dust by @3floyds at @thebeerbistro — http://t.co/q2GBTfvyQr 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


Drinking a Summer Ale by @GooseIsland at @thecubbybear — http://t.co/k7ZaLjQceB 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Wife and kids are gone tonight so what am I excited about? Getting a #steak and #craftbeer at @WFMphoenix and having a quiet evening! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


buy us beer 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.28, 0.72] 


Eve

I do not/cannot drink alone, I'm a social drinker. I was generally saying, drinking alone is a warning sign for alcoholism. That's all. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Got into a argument with a 60 year old man at a party and threatened to throw my beer bottle at him 😂 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


Working on Saturdays should be illegal! I  have no motivation to move at work right now. But can't wait for beers with the lady tonight 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Smoke drink breakup x Mila J 🎶🎶 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Im a total Differnt person when I drink 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.26, 0.74] 


Woke up still drunk racing to work again bc I didn't wake up fml 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.14, 0.86] 


Drank all night, and I'm Still up 
 Original label:  1 Prediction:  1 
 Probabilies


I drank something besides beer tonight and survived. Hell has frozen over 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


all I want to do is drink beer but I don't even feel like doing that 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


Drinking a Nice Life by @OtherHalfNYC at @theponybar — http://t.co/f5d7RQnfqy 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking a Pils-Noir by @SBCbeer @ Shakedown BBQ — http://t.co/5XWScEp4qS #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.12, 0.88] 


So damn Juicy!!!! - Drinking an Alien Church by @tiredhandsbeer at @tiredhandsbeer  — http://t.co/ZXVx7c7Gbq 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


Drinking an Old Rasputin by @NoCoastBrewCo @ The White House — http://t.co/IHUh5opPlr 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


4 weeks in a row. #letsgohawks - Drinking a Daisy Cutter Pale Ale by @halfacrebeer at @villageta

 Probabilies:  [0.12, 0.88] 


She only smokes when she drink,  she only drinks now and then.  Now and then when she's tired,  of being let down by men 🎶🎵 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.56, 0.44] 


Waking up drunk &gt;&gt;&gt;&gt; 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


So I was a little drunk last night. ¯\_(ツ)_/¯  #day2 #samf 
Time to take on day 3 💪🏼 @ Soldier Field https://t.co/eAnYSdlzdp 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


Woke up with half a bottle and a blunt 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.47, 0.53] 


last night i scratched my favorite raybans while drunk. 😎😭 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.14, 0.86] 


Drinking a Revenge of the Emu by @Cuzett at @stgambrinusbeer — http://t.co/znB03UfdCN 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Crutching around when drunk is the hardest thing I've ever done 
 Original label:  1 Prediction: 

 Probabilies:  [0.36, 0.64] 


I didn't get carded at the liquor store yesterday because I was told I have a good aura ✌🏻🌻 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.1, 0.9] 


Pretty sure I can drink a margarita any hour of the day 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


Drunk on a Monday 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


drunk squinty eye out in full force @ Hopsmith Tavern https://t.co/decWTeRKND 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.54, 0.46] 


Me: *coughed while drinking my Oreo shake* 
Me: Oo spicy 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


considering going out and drinking by myself since yous are all boring and wanna sit in and stair at walls 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.14, 0.86] 


Really wanna do a party where we use broken @Iphone s as drink tickets for @MollyRhinestone s bday!!!!! 
 Original label:  1 Prediction:  1 
 Probabilies: 

 Probabilies:  [0.23, 0.77] 


@CMWhitehall got beers waiting for you downstairs, where TF you at? 
 Original label:  1 Prediction:  0 
 Probabilies:  [0.69, 0.31] 


Delta tried it today with them ancient flight attendants too!! I was in the air for 1hr with not drink Bih.. Then Ms Pearl bumped me 10xs 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


Drinking a Czech Mate by @nodabrewing at @nodabrewing — http://t.co/KuarTbBTWo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


Becoming a morning person by creating my own delicious drinks
And also by being forced to work at 8am or earlier everyday but still it helps 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


Need to find someone who will drink beer and watch Grey's anatomy with me 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Omg I am sooootired. NOKoreanFood2day, orderedExquisiteIndian2myelevator instead. I start work 2morrow, late night club hrs, cant

 Probabilies:  [0.5, 0.5] 


Me when im drunk with Bae😊😊😊 he get all scared @ Whittier, California https://t.co/7SzS8P1vOP 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


I was so drunk when I did this http://t.co/roxfOwQOPv 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.26, 0.74] 


Made quick trip to dollar general at the lake to purchase a table big enough for beer pong. Best 35$ eva spent @Madalyn_Rector @emilyyydawn 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.49, 0.51] 


I wanted to go to the key! show at beer and tacos :( 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


Drinking a Newcastle Brown Ale by @HEINEKEN_UKCorp @ Cantina 76 — http://t.co/J4Nmi4qNQE #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


The first time all of my friends get drunk 2 after we move back to school is going to be such a wonderful shitshow 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


An early #F

 Probabilies:  [0.52, 0.48] 


My day w/ @AmericanAir is off to such a bad start, I'm drinking a 9:25a Ruby's Bud Light. #UpForWhatever @WebberSteph http://t.co/0Ps7ijfn0F 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


I wanna chill by a body of water and just have a beer tonight or soon this coming week would anyone be down to accompany me ? 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.09, 0.91] 


I always know I went hard when I wake up with an opened beer I didn't finish within reaching distance 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


#OhHappyDay...got my drink from the Dutch Bros for free today! The crew there is awesome!! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.31, 0.69] 


Drinking a Lievre Saison W/ Kumquats by @laaleworks @ Vibiana — http://t.co/nz3TVXMlby 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


I remember when we were drunk and I lost my wallet and Ron paid for my jack. Clutc

 Probabilies:  [0.24, 0.76] 


Mayor Moser examining his Avenue in a different light tonight. I do not understand how some people come here and don't drink. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.42, 0.58] 


Thankfully I dont drunk post, because what might look good with beer goggles might not look good with sober eyes 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


How tf did i get this drunk 😂💀 http://t.co/vCJEAdqzwD 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.3, 0.7] 


So drunkkkkkkkkk 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drunk people are fucking hilarious 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


Drinking a Miller Lite by @MillerCoors @ Altas Horas — http://t.co/v9EjF86ic3 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


If you ain't getting drunk get the fuck out the club!! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


Drinking a Gams-B

 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


Checking in @VIVO_Lounge stop by, Ariel is buying drinks!!! http://t.co/pTbANUIDrE 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.28, 0.72] 


I've been drinking for 11 hours straight. #dying 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Drunk ping pongggg!! 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.26, 0.74] 


#RushvilleDrunk #DoBetter 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking Beer out of the bottle feels weird 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


I'm surprised the beer emoji is not higher on my frequently used emoji category 🍻 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.52, 0.48] 


"I need to give up beer and take up vodka." -Eva 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.28, 0.72] 


My uncle would be the one to bring a bottle of moscato for himself when everyone else is drinking beer. #

 Original label:  0 Prediction:  0 
 Probabilies:  [0.65, 0.35] 


Wish I could be home to drink a beer with my dad got Father's Day. I guess I'll just be grateful that I have such a good dad. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.09, 0.91] 


Drinking a Saranac 1888 Root Beer by @saranacbrewery @ Kill Buck Inn — http://t.co/q4ORivdPO0 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.27, 0.73] 


Fuck I was ripped last night - Drinking an Insomnia IPA by @WiensBrewing at @disneyland  — http://t.co/tm74FkgMG5 #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.05, 0.95] 


Sooooo damn good - Drinking a Naughty Sauce by @noblealeworks at @noblealeworks  — http://t.co/KCzqoHry4b #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


drink the pain away 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


Don't play truth or drink when the significant other is there lol 
 Original label:  0 Prediction:  1 
 Probabilies:  [

 Original label:  0 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


Drinking a Paradox Compass Box by @BrewDog at @cicerone — http://t.co/Yx68keMjTg 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


party tonight bottles provided 👌😈 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.46, 0.54] 


Drinking a Musketeer by @EarthBreadBrew at @earthbreadbrew — http://t.co/Znr9w4nXrW 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Grapefruit Can'd.... - Drinking a Grapefruit Sculpin by @bpbrewing @ Underdog's  — http://t.co/ppXPl8zH8w #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


When your mom is like what's been wrong with you today , did you drink to much last night 😂😅 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.75, 0.25] 


I don't even like Jack but I'm drinking it to celebrate my first successful day at my new job! http://t.co/dCpAnovcbO 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


I 

 Original label:  1 Prediction:  1 
 Probabilies:  [0.08, 0.92] 


Beer with a view - Drinking a Samuel Adams Porch Rocker by @SamuelAdamsBeer @ Mcfingers Lake  — http://t.co/w5Trx4XCnJ #photo 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.3, 0.7] 


Two drinks for $14 and then one or two bought for me on like any given night?? Shittttttt 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.24, 0.76] 


Drinking a Pistachi-YO Saison by @AZWBrewingCo/@GCBrewery at @azwbrewingco — http://t.co/0vw7Gc21jI 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


man I swear I could drink that shit all day 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Finally cleaning my room so Andrea has a nice place to pass out in after I drag her drunk ass home this weekend 💁🏼 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Yeah this getting drunk by the fire thing is a go lol 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.14, 0.86] 


 Original label:  1 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


Mannnn i was taking moonshine shots last night 50% alcohol and i didnt even get drunkkk. Pro ? 👼🏼 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Drinking a Pulsar by @BottleLogicBrew at @bottlelogicbrew — http://t.co/RgQaoxLtHz 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.29, 0.71] 


Drinking an Anti-Hero IPA by @revbrewchicago at @loumalnatis — http://t.co/nLDRicC3mh #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


Drinking an Old Style by @pabstblueribbon at @dinosaur_bbq — http://t.co/eAySzYi8Hk 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Drunk on a Wednesday. Shit 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


WHEN UR DRUNK BUT U KEEP DRINKING http://t.co/aLirIZWqiR 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.31, 0.69] 


Wish I could explain to u how hard it is pretending I have good taste in beer... #sho

 Probabilies:  [0.51, 0.49] 


Drinking &amp; relaxing is on the list for the night 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


I've been wanting a drunken night out with ghetto music for sooo long. &amp; tonite its FINALLY gonna happen. ~Yasss qween~ 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


*writing resume*

"I can drink a fifth of liquor without puking and can still type a grammatically correct sentence" 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


THIS DRUNK ASS MAN JUST FELL DOWN 2 ROWS OF SEATS ONTO ME :) 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.54, 0.46] 


Drinking an Ideation by @BottleLogicBrew at @bottlelogicbrew — http://t.co/XGf8RjXjO1 #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


Drinking a Hunter Orange by @18thStreetBrew at @twentytap — http://t.co/3fhjG4KSFH 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


So beers tonight ? 
 Original 

 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Drunk 🔶🔶🔶 #EdSheeran #X @ Hollywood Bowl https://t.co/zpjqOPQtP5 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.26, 0.74] 


Drinking a Five Mile Ale by @2ndStoryBrewing at @2ndstorybrewing — http://t.co/djq1nXY3nX 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Catch me slinging drinks tonight at #DollHouse #BarTending #Bartender #BarFun Come play will all my… https://t.co/oxfQYZ1O0a 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.49, 0.51] 


Who needs a beer right about now? 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.29, 0.71] 


. @OasisTXBrewing Meta Modern is back! Just in time for your weekend day-drinking. #TGIF 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.29, 0.71] 


Just asked the lady at the BK drive thru if they had Coors Light. Guess they don't bc I'm drinking Dr. Pepper🐣 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.57, 0.43] 


BWOY IF YOU DON

 Original label:  0 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


If frankie lays down next to me and has beer breathe he's sleeping on the floor. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


A dead dog was found in the wine vat, so... Onward with the winery tour! #FatherBrown 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.51, 0.49] 


Late night food...with some friends...after a night out drinking...good times, with awesome people! =) ♡♡ https://t.co/Wc9YGJ13Ur 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


First time drinking up with my older brothers was hella cool 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


I just payed &amp; i'm already gonna spend it on alcohol 😰😂 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


It's 7am and I find my dad cleaning out my beer fridge ....... Um Tf ! 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


My favorite part of the night had to

 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


So good - Drinking an India Pale Ale by @MarbleBrewery @ Coop's Place  — http://t.co/pPf8NxXHp9 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.15, 0.85] 


There's literally more beer than anything in this kids party smh 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.59, 0.41] 


made JJ Sulinger a drink whatts gooood 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.37, 0.63] 


Drinking a Festina Peche by @dogfishbeer at @petrol_station — http://t.co/m51tZTtuYC 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.12, 0.88] 


Watching a show and I see them drinking Clearly Canadian...woah! Bring me back to my childhood much! I wish I had some right now😩 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.09, 0.91] 


Drinking a Mosaic Yum Yum by @noblealeworks at @noblealeworks — http://t.co/PkHjWS9q7i 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


lord they done fucked a

 Original label:  0 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


We are getting our drink on! #newyorkcitylife  #NewYorkCity #GayPride2015 #NewYork4Eva  Piña Colada… https://t.co/XIQeal05Jn 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


Liquor before beer, you'll never be sicker. 
Beer before liquor, you're night will go by quicker. 😜🍻🍸🍹🍷 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.7, 0.3] 


Frozen beer on top of beer!! Yum!! - Drinking an Ichiban (Ichiban Shibori) at @urbanbelly - http://t.co/8vWkxoe8Q0 #photo 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.24, 0.76] 


The Blake found beer from Kenya! #beerlovers #disneybrewski #animalkingdom #tuskerlager… https://t.co/QbC9LiGdch 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


Baby is u drunk did u have enough 
 Original label:  1 Prediction:  0 
 Probabilies:  [0.61, 0.39] 


@KaraFranker at vino volo having a drink, come join us! Don't have your # 
 Original label:  1 Predic

I'm just down to get drunk and sit by the river 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


I need a drink. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.03, 0.97] 


I guess imma get drunk tonight 😈 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.05, 0.95] 


Drunk 😋👍🏼 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


When you're drunk at 6:30...it's gonna be a good night 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.28, 0.72] 


Fina get pissy drunk all weekend. 🍹😛😋 don't judge me tho. But really dgaf it u do 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Beer beer beer more hot pies sweeney sweeney swooney 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Get drunk and rap kanye till I past out 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.11, 0.89] 


Back to what I was doing and that's getting drunk 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.08, 0.92] 


Dru

I need a damn beer 🍻 #thirstythursday 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Drinking wine :) 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.1, 0.9] 


I'm kind of drunk playing with Kubrick 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.19, 0.81] 


I need a beer 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.03, 0.97] 


My drunk stepdad is supposably talking to God out loud. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.55, 0.45] 


wish i was drunk right now 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


i wanna get drunk and cry. :3 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.07, 0.93] 


I move in slowmo when in drunk 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


I'm thinkin day drinkin this weekend 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.06, 0.94] 


Need drinking partner 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.49, 0.51] 


A night to 

Noche de Karaoke en Montezuma venga y sea la estrella de la Noche.. Shot de Tequila Gratis A Todos… https://t.co/3cvlIdgCYf 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


See a virtual tour of my listing on 262 N Route 9 (Waterfront) #Eagleswood #NJ http://t.co/LGttj4qCeT #realestate http://t.co/sbV6JFnLI0 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


Just added Founders Curmudgeon Old Ale 2015 bottles. See our full beer menu: http://t.co/xHsKGFSCVF #BeerMenus 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.89, 0.11] 


@Odonovans_Pub I may come check you out on Sunday, anything good going on there that day? 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


I judge My Gf For Hangin Wit Ppl that are like 14/15/16 but i i dont look at how old the ppl i fw are 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.55, 0.45] 


Parties are cool to makeout with women but fucking them is a no go if they drinkin, I'm a no cha

 Probabilies:  [0.71, 0.29] 


YOU TAKE THESE DRINKS DOWN, DONT LET THEM TAKE YOU. 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.65, 0.35] 


The bday boi and girl getting it in. @ RIC'S Restaurant &amp; Lounge https://t.co/c134ELo6im 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


My girl the realest person on my team if it ain't her 🌵yall 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.69, 0.31] 


Drinking a Divine Reserve #13 (Bourbon Barrel Aged) by @saintarnold at @saintarnold — http://t.co/rWbqsmZtFi 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Love this place!!!!! @childresswines @ Childress Vineyards https://t.co/ITNxvAKjUl 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.47, 0.53] 


#Budweiser ice cold at #BennysOnTheBeach #LakeWorthBeachFL @BEERWlTHAVIEW http://t.co/Sq2tiuEBDB 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.79, 0.21] 


Nothing to do? Come on down to Exchange Place. Food, beers, music. 

 Probabilies:  [0.11, 0.89] 


Dinner at a British pub (@ Cock &amp; Bull British Pub and Eatery in New York, NY) https://t.co/ZMHd0cqrma 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.59, 0.41] 


@BartenderHQ Celebrating #WorldGinDay with rare obscure #Gin and creative cocktails #FordsGin Enjoy! http://t.co/RNhjJNpuag … #mixitup42 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.81, 0.19] 


If you're in #Sales and want to work at CORT Business Services Corp., check out this #job: http://t.co/8mCTezB1g0 #HasbrouckHeights, NJ 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.79, 0.21] 


@LoveACocktail Celebrating #WorldGinDay with rare obscure #Gin &amp; creative cocktails #NOLETSGins Enjoy http://t.co/RNhjJNpuag … #mixitup42 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.87, 0.13] 


#BeerThugs beerthugs #BeerClub  always welcome at the Tasting Room in #Covina 🍻 @ REV Brewing Co https://t.co/rPPQLdw3Lu 
 Original label:  0 Prediction:  0 
 Probabilies:  [0

 Probabilies:  [0.83, 0.17] 


I'm Hosting #ChickenNBeer This Thursday @ Social Junkie Everyone come thru and Turn up with ya guuurlllll one time.😜 http://t.co/nEd9FmTmUB 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.61, 0.39] 


@gstevenson508 😂 thank god an angel came to my rescue! Send booze 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.26, 0.74] 


Tomorrow's list:
◇WAKE UP
♡LAY BY THE POOL
◇TAN
♡TAKE MELS TO WATCH "INSIDE OUT"
◇TAKE OZZY TO DINNER FOR HIS BDAY
♡GO OUT DANCING/DRANKS 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.67, 0.33] 


@younginuly lol hell naw them niggas outta there young niggas don't even smoke reg these days 
 Original label:  1 Prediction:  0 
 Probabilies:  [0.71, 0.29] 


This bottle always tastes better http://t.co/dRMZs7GNeX 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.6, 0.4] 


Summer Books and Summer Cocktails http://t.co/6kklPHhtb3 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.7, 0.3] 


Warriors or Ca

 Probabilies:  [0.44, 0.56] 


On this rainy day remember,  Wine on the Mountain is Indoors... Buy your tickets now http://t.co/pw4iL3TJDF http://t.co/iR45ZtUSjr 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.82, 0.18] 


Join Us For Our Bottomless Boozy Brunch From 11am-5pm At VB3 Restaurant, Sports Bar &amp; Lounge

Enjoy a… https://t.co/hk3g9D4BrB 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.82, 0.18] 


On a fantastic beer tour with Micah @SoPinesBrewing! @NCVetBiz Micro-Networking Event. So much great info! http://t.co/pyt620S9uq 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


U Can Take The Men Out The Hood, I'll Let Y'all Finish The Rest... Prime. 2for1Drinks. .25CentWings.… https://t.co/lVZ6X0d2EQ 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.67, 0.33] 


@__CrazyLove @konaflower  I'll bring the tequila :) 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


When you pick your beer out on the basis of branding &amp; 

 Probabilies:  [0.18, 0.82] 


Someone is drunk on champagne. @_Philly_Talk 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


@mrmichaelball Having a drink (or 2 or 3) in your honor! Congrats!!!!🍸🍸🍸 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


the main problem with cheap wine is it tastes like it was poured through a boot 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.53, 0.47] 


Wine alert! @mariesbistro has a huge deal on Albis and Haras....limited bottles, best wine deal this… https://t.co/RoMHeOq95U 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


On some shopping sprees, drinks, and a powder stash 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.36, 0.64] 


@drestor17 @jazzlyn_dgaff @kaylalagaso fuck beer ! Henny n patron on my good days ! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Maybe I drink too much when I overthink but lately I overthink just to have a reason to drink😔 
 Orig

 Probabilies:  [0.56, 0.44] 


Sometimes you just want an extra large glass of wine🍷🍷🍷 #wino 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


Pizza boy beers #pbw2015 (@ Bainbridge Street Barrel House in Philadelphia, PA) https://t.co/xeJjDSTA9M 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Get out of the nasty weather and enjoy delicious kosher steak and cocktails at Talia's tonight. Great romantic dating spot. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


Monday Night at Montana's Bar &amp; Grill Marietta​! Tonight we have Domestic Drafts &amp; $3.00  House Margaritas!!! Don't miss out! 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.51, 0.49] 


@mskayteegrace just poured four loko into her cup of whiskey but at least she's in the living room with her best friends #rip 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.66, 0.34] 


Groove on over to @SouthportIrving f/ #DameThursdays tonight - good times w/ friend

 Probabilies:  [0.4, 0.6] 


She got a pool for her feet! #notherfirstrodeo @ Brandywine Food &amp; Wine Festival https://t.co/qfz5NfNOMr 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.32, 0.68] 


Now that I'm no longer a student athlete I can finally tweet this. I NEED A BEER. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


Melted cheese! This Sicilian recipe will melt your heart, too. http://t.co/kNZdmKjJuu Enjoy with red wine. Swoon. http://t.co/4LyYr6usQy 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.84, 0.16] 


whatchu want to drink I know you hate being sober! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.39, 0.61] 


Drinks Bfore lunch!!!! http://t.co/xOK6LzChbf 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


You melt me like ice and whiskey with those blue flame looks that you give me 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.83, 0.17] 


Mia Steiger, took Sonoma Food &amp; Wine tour, copied &amp; 

 Original label:  1 Prediction:  1 
 Probabilies:  [0.28, 0.72] 


Good day for some brown bag booze! Birthday presents all around. #neighbors #brownbagginit #rhinehall… https://t.co/T9aTBb1oLX 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.58, 0.42] 


Guys I love @melfalll more than I love beer 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


Columbus night life is booming when you're drinking age. Arena n shit  https://t.co/JdpxeJMYyQ 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.7, 0.3] 


Wait, I get to go listen to an interesting speaker WHILE drinking at a bar? I’m in. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.11, 0.89] 


@queersandwich Food, necessity. Alcohol........also a necessity. I see your point. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.46, 0.54] 


Smh I did nothing but drink n smoke yesterday my stomach so empty my shorts just hanging of my hips 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.7

 Original label:  0 Prediction:  0 
 Probabilies:  [0.77, 0.23] 


@jowanuh besties until the rapture. And even after that we'll be chilling in heaven and hopefully there's weed allowed there and alcohol! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.48, 0.52] 


Starting off the day right w/ a build your own Bloody Mary bar. Later in the day:  some sushi making, whiskey, and anniversary dinner. 7yrs! 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.52, 0.48] 


VOGA FRIDAYS HAPPY HOUR 
4pm TO 10pm 

$5 MIX DRINKS
$3 BEERS 
$15 PITCHERS OF MOJITOS OR SANGRIA
$80… https://t.co/FWitzxUlJZ 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.9, 0.1] 


@LasagnaChelsea generally I'll have pasta (but everything is good) and of course lots of wine 🍷 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


Not too late to purchase your tickets for this upcoming Monday. Beers, Spinal Tap,  food, and a good time! https://t.co/Qm8NWkcmE8 
 Original label:  1 Predictio

 Original label:  0 Prediction:  1 
 Probabilies:  [0.41, 0.59] 


@dat_boi_dev lol if sylvia will allow me too 😂😂😂 guess that means I'm gonna drink up! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


lmfaoooooooo bless my friend for buying me my next drink because I WISH A NIGGA WOULD 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.13, 0.87] 


Loving this beer with lunch - like lemon rind on the anise but ... (Triporteur From Heaven) http://t.co/PEeiteGOyl #photo 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.36, 0.64] 


Bruh I just spilled this big ass cup of liquor all over the carpet. I'm going to sleep 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.21, 0.79] 


The bouncer let me into the bar and said "please don't drink".. Yes sir 😬 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.61, 0.39] 


Instead of BYOB, I like BYOV... Bring your own vodka 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.53, 0.47] 


Oh yes. From date

 Original label:  0 Prediction:  1 
 Probabilies:  [0.44, 0.56] 


I just want some bomb food,  wine, and a foot massage  😄 too much?  lol 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


@laurabaverman @exitevent - Just havin' fun. Good luck! We will have beer from @ironcladbrewery , beautiful two story brewery and ice cream 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Wine tasting with the ladies! 🍷 @ Baldwin Vineyards https://t.co/e0OdizrnVJ 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


Winery and brewery, something for everyone! (at @WagnerVineyards in Lodi, NY) https://t.co/fgf4iV7C0Q 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.78, 0.22] 


@AirDani123 lol I can help you get that way! I just need a bottle of makers mark! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.25, 0.75] 


I took 56 bars all in 1 month nigga &amp; I'm still drankin' -@1future #anotherday #anothercity #newyork… https://t.co/Xm1sA1

 Original label:  1 Prediction:  1 
 Probabilies:  [0.46, 0.54] 


Last night of 34 was perfect. My person, live music, and cold beer. Best! Love you kasims7 @ Klipsch… https://t.co/2lQoLerYo9 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.56, 0.44] 


@JonHeymanCBS Go to bed Jon, you're drunk.......Love your baseball coverage though :) 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.69, 0.31] 


I do not want to see anybody that is giving @Caitlyn_Jenner a hard time at gay pride just cuz it's a reason for you to dress slutty n drink 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.4, 0.6] 


Random dumbass thought he had a chance with my cousin at the bar. He bought our drinks. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


@DominantMrGrey exactly! How much of that will you like in your daily drinking? @DaiGurren_Erica or maybe some Heineken? 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.77, 0.23] 


@bdentrek @RunTheBasesMLB @ghostfa

 Original label:  0 Prediction:  1 
 Probabilies:  [0.51, 0.49] 


@darnethel you told me lets go to bdubs for a beer. That turned into 4 tall boys and 2 shots of patron. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


Enjoying a Eliza5beth Midwest Farmhouse Ale by @Prairieales @ Villain's Black Market Craft — http://t.co/jOPTiN0hSX #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.24, 0.76] 


@Padronah So he could go out drinking or whatever. :( That is sad. 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.63, 0.37] 


@bmock14 how's that fun while you're drunk ? you'll die 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.89, 0.11] 


@branteflores haha drink a lot of wine. Or beer. Or tacos.... 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.42, 0.58] 


@paul_lander #getamoviedrunk Bang the Rum Slowly 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.59, 0.41] 


Slow like the Mississippi strong like the fifth of whiskey~ 
 Or

 Original label:  1 Prediction:  1 
 Probabilies:  [0.18, 0.82] 


"@ShutUpKyle22: @AustinTran_ .. Are you ok?" I don't know, fuck stick spiked my drink 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.55, 0.45] 


And eat food &amp; drank Moscato https://t.co/mC6RSS7A2W 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.36, 0.64] 


I'm at Hana Wine &amp; Liquor in Brooklyn, NY https://t.co/65hBTGFxEs 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


Update: there is a boy who definitely isn't 21 pouring alcohol into a mcds cup on the metra 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.71, 0.29] 


@Taylor_GangClos @PLAYAMADEMEXCN I'm down to drink 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Beers and skylines. #summernights #cheers #nyc #onaboat snikkki_minaj @dkurtin @ The Frying Pan - NYC https://t.co/KlYTjJG0kT 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


Meeting w benefits. #beer (@ Draught in Cha

 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


@ICantWitPeople lol well she does keep telling me maybe if she's drunk enough... Hmmmmm 😈😈 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


@ITSFRANCO94 😂😂😂 hell naw I'm not drinking too much tonight 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.12, 0.88] 


@mattwright__ @zachesor We ended up trying tequila/tonic with radler AND Campari ice cubes. Also worked with gin. Simple and awesome. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.24, 0.76] 


@FantaGnocca @ClaudiaRomani @sportnotizie24 all drink  to both.Score and u my Lady 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.37, 0.63] 


@SeanMonaghanPDX let's definitely meet up before or after for a beer! You have my mobile right? 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


Drinks before sunset 🍸🍸☀️#billturns50trip #southcoast @ 180 Blü https://t.co/D9UBEtNmNq 
 Original label:  1 Prediction:  1 
 Proba

 Original label:  1 Prediction:  1 
 Probabilies:  [0.07, 0.93] 


I'm doing a demo/tasting at Ale yeah in Decatur Saturday 1pm to 3pm come by and try some samples while they last. http://t.co/6qVhdsl5OS 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


If you see this chick today be sure to have a shot of whiskey in hand!! Happy Birthday to the best… https://t.co/6BUiv9emu3 
 Original label:  1 Prediction:  0 
 Probabilies:  [0.7, 0.3] 


Join Sabrina @Atmis for a free tasting #LanguedocRoussillon #wines 6 to 9pm today https://t.co/J2RO4BNSTh http://t.co/z5ZO12YmGu 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.74, 0.26] 


The @bluewolftavern has Seafood Friday with Walleye Francaise or Beer Battered Cod with homemade Mac &amp; Cheese. 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.69, 0.31] 


..It's that day &amp; hour of the week when "Wings'n Beers" taste oh so good! #HappyFriday 🍻😜 https://t.co/UHmjPR2hz8 
 Original label:  1 Prediction:  1 
 Pr

 Original label:  1 Prediction:  1 
 Probabilies:  [0.34, 0.66] 


Another update.  This was the best high alcohol IPA I have had yet.... (Hop-de-Ranged) http://t.co/qx8fKlpBrU 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.38, 0.62] 


@tran_christy no, who drinks at 1 on a Saturday you're so weird 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.66, 0.34] 


Wine time (@ South River Winery &amp; Vineyard in Geneva, OH) https://t.co/3BNCaCbrt1 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.52, 0.48] 


If you kill me at work you win one free drink of your choosing. Any size. I'm there from 12:45-5:30 today. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.6, 0.4] 


Drinking an Alpha King by @3floyds @ Hopson Hill Brewpub &amp; Lounge — http://t.co/qQyYpq8GuN #photo 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.2, 0.8] 


Tomorrow we celebrate THE DAD! Dads BYOB (bring your own baby) and get 1/2 off craft beer &amp; wine from… https://t.co/BlTOlnqV

Ahhhhhhhhhh why did drink so much and so much ... 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.22, 0.78] 


@DannyDeraney Get inside quick for the free beer. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.48, 0.52] 


I need to find someone who can hold her liquor and show me a fun night 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.3, 0.7] 


It's getting to the point where I don't know if you actually want to talk to me or you're just not sober. 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.56, 0.44] 


@ @manwhale_corona for making me feel better&gt;&gt;&gt; 😂😂 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.17, 0.83] 


Never eat too much before going to a kickback if you expect to drink... Trust me it will back fire 😭 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.33, 0.67] 


@Samy_15 @doitbig___ the food was good lol the drinks 😁 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


Jesus Christ when don't I want t

@niemanmusic was excellent tonight. @ dba256 Wine Bar Lounge https://t.co/XRZVglzb7N 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


dad puts his alcohol mixed drinks in milk jugs &amp; me not realizing I just poured it in my cereal &amp; started eating it. fml 😕 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.41, 0.59] 


@lost_one25 lmaooo you've never seen me drunk off henny I'm a different person lmaoooooo 😭😭😭😭😭 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.29, 0.71] 


*Walks into babe's house*
"Where's your dad keep his beer? " 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.77, 0.23] 


You've had a great evening,haven't finished off the wine bottle Pour into an ice cube tray &amp; freeze Perfect for sauces, waste not want not! 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.35, 0.65] 


@TayRe you just assumed that at 1a.m that I'm automatically drunk... You stand corrected good sir!! 
 Original label:  1 Prediction:  1 
 Probab

Swing! So much fun last night at Jazz At Lincoln Center's Swing Summer Cocktail Party.… https://t.co/G55Cps7fOq 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.57, 0.43] 


I was hoping to be a victim of a qualifying crime this morning but the little drunk guy with his shopping cart kept his distance 😐 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.45, 0.55] 


@DuaneBS u better swallow that beer faster than you swallowed @Jordan_Palmer_ semen last weekend 😂 
 Original label:  0 Prediction:  0 
 Probabilies:  [0.66, 0.34] 


@ConnellCaleb She's being a little ho ho, just wait. I hate nick so much hahaha 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Make it a special day w/ @BesseratB #champagne @WineSpectator http://t.co/cYh0TGnr1w 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.56, 0.44] 


Playing dominoes and drinking...#lifeisgood along with 200 followers....thanks to @MattieLBreaux http://t.co/NhYDO88m4g 
 Original label:  1 Prediction:  1


@quixoticideal he's going to catch feelings like....well...like anyone who listens to Sam Smith after a night of 3rd wheeling and drinking. 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.23, 0.77] 


went from fallin in love to drunk and fallin apart 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.31, 0.69] 


Drink for a cause!  We are raising funds for surfrider, protecting our coast and environment. We are… https://t.co/GZYrmr9hE3 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.5, 0.5] 


Alcohol makes everything so much.... Better? 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.41, 0.59] 


drank up in my cup but that don't mean that I fuck slowww 
 Original label:  0 Prediction:  1 
 Probabilies:  [0.16, 0.84] 


@Mo_was_there_yo @BlackPplVines @iplay_keys96 @Hi_Sadiess @tashnnv STG I feel like I'm all in one when I'm drunk and sober 😂 
 Original label:  1 Prediction:  1 
 Probabilies:  [0.25, 0.75] 


I got the love birds chirpin at the window but I

On first glance it seems that when the classifier disagrees with the original label, the probabilities of either 0 or 1 are quite close. We will look at that step next.

In [19]:
alc_fp_disag_tweets = df[numpy.array(subset_vec_alc_fp) == 1][numpy.array(alc_fp_preds) != numpy.array(fp_lab)].text
alc_fp_disag_labels = numpy.array(fp_lab)[numpy.array(alc_fp_preds) != numpy.array(fp_lab)]
alc_fp_disag_preds  = numpy.array(alc_fp_preds)[numpy.array(alc_fp_preds) != numpy.array(fp_lab)]
alc_fp_disag_probs  = numpy.array(alc_fp_probs_round)[numpy.array(alc_fp_preds) != numpy.array(fp_lab)]

for disag_tweet, disag_label, disag_pred, disag_prob in zip(alc_fp_disag_tweets, alc_fp_disag_labels, alc_fp_disag_preds, alc_fp_disag_probs):
    print(disag_tweet, "\n", "Original label: ", disag_label, "Prediction: ", disag_pred, "\n", "Probabilities: ", disag_prob, "\n\n")

Beer fans need their @ColumbusBrewing Bodhi. I'm making another @tdg_powell trip for the #MemorialTournament http://t.co/Z9u3NrCBea 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.49 0.51] 


Stone Cold use to be the baddest MF in my book lol dude use to get hype; whip your ass and waste a case of beer in the ring 😂 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.48 0.52] 


Now @iamjohnoliver has to drink a Bud Light Lime #SeppBlatter 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.5 0.5] 


Sweeter than muska dime wine 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.36 0.64] 


Business hours are between 1 1/2 and 5 drinks. ;) 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.56 0.44] 


So for now, no drinking for the foreseeable future! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.38 0.62] 


Drinking an Osiris Pale Ale by @SunKingBrewing @ Union Station — http://t.co/7eDLi4vkF0 
 Original label:  0 Prediction:  1 
 Probabiliti

 Original label:  0 Prediction:  1 
 Probabilities:  [0.61 0.39] 


I forgot how much I fucking hate beer 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.13 0.87] 


I picked up my moms drunk ass from blue 32 and took her to the gas station to get me drinks and she stopped to talk to lil kids outside 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.54 0.46] 


Well since I'm dd I can't get drunk but I will get high af 💃🏽 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.07 0.93] 


I always get sleepy when I'm on that's why I don't drink😂 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.28 0.72] 


Ive been drinking too much benadryl to go to sleep..i need it though i think too much when its time to sleep :( 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.11 0.89] 


I like my boyfriend when his drunk lmao 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.27 0.73] 


When Gavin makes me his drinking partner without my knowledge💀 
 Origina

 Original label:  0 Prediction:  1 
 Probabilities:  [0.31 0.69] 


Drinking a Hoosier Ale by @hoosierbrewco at @tomtaproom — http://t.co/ht8V94lmXP #photo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.19 0.81] 


Let's drink and do stupid stuff 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.34 0.66] 


Drinking an IPA by @stbcbeer @ Blue Ridge Trail Golf Course — http://t.co/5bPp0V62Jf #photo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.23 0.77] 


Talking wedding at @thorndalecraft - Drinking an Union Jack IPA by @FirestoneWalker @ The Craft House  — http://t.co/9rX6oQqDDk 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.22 0.78] 


When the tattoo artist buys you a round of drinks 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.64 0.36] 


Drinking beer is my thing. But I don't believe in smoking. Give me some damn whiskey or cigarettes! I don't care! I smoke some but w/e! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.37 0

it's ok to be drunk on the lake @ High Rock Lake, NC https://t.co/h4tP2B6v6m 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.53 0.47] 


Bought a Adam Lallana jersey. Cant decide if I should buy a mini fridge for my room to fill with beer or a puppy. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.32 0.68] 


Drinking an Old 21 by @brewkettle at @localroots09 — http://t.co/f1DTZcqA5E 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.37 0.63] 


"I'm not drunk I just did twenty jumping jacks" 😂😂 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.14 0.86] 


A drunk guy just told me I have the cutest nostrils he's ever seen and I have the perfect nose for a nose ring ONG AW #blessed 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.48 0.52] 


Drinking a First Anniversary IPA by @OtherHalfNYC at @mugsalehouse — http://t.co/SBKRgHr7qE 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.28 0.72] 


its too early for my family to be drunk already 



drinking on an empty stomach lmaoooo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.21 0.79] 


I picture myself also having some sports related thought and the thought of having a beer before I realize what's going on. LOL 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.26 0.74] 


I have a fucking alcohol class for 4 hrs today 😭 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.32 0.68] 


There might be a shortage of Corona beer this summer.  And even worse news:  there will be a surplus of Natty Light. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.6 0.4] 


The chance of me wearing the same thing from yesterday totally relies on how much I drank last night 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.12 0.88] 


#supportyourlocaldive, 1696 2nd Ave btwn 87 &amp; 88. Drink specials all night! 8pm. 13 lines getting ready a beer explosion coming soon! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.49 0.51] 


Drunk ugly chick 

 Probabilities:  [0.28 0.72] 


Snapchat's dangerous when people get drunk and think you wanna see parts of them that no one ever wants to see 🙈😐 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.79 0.21] 


I put Act inside my drink, they call it medication 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


My ex needs to stop drunk calling me srsly YOU'RE DEAD 2 ME DAWG 😴 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.44 0.56] 


King of beers.

#straightmen http://t.co/KwgU7lk0Pb 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.36 0.64] 


Drinking a Summer Ale by @greenportbrew at @coopersnyc — http://t.co/JMJwkZLzIL 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.31 0.69] 


I managed to spill my entire drink all over my lap at old Chicago so that's cool 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.42 0.58] 


Temper flair ups n tantrums, annoying neighbors and bad timing..Blame it on the alcohol. 
 Original label:  0

 Probabilities:  [0.19 0.81] 


Getting ready for the @U2 concert in Chicago tonight by drinking @GooseIsland 312 http://t.co/9WR4qJwZMX 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.3 0.7] 


Having a Beer.. Ommegang Fleur Houblin #BlackandWhite #noir #beer #craftbeer #pictures #barpics… https://t.co/aRR13uugrG 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.62 0.38] 


I can still wear kids clothes and my bestfriend doesn't even get carded for alcohol fml 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.54 0.46] 


Like wow you sit around a drink all day and don't go to school? Wow I just wanna congratulate you for being such a fuck up 😊 congrats! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


Not a great beer. Little too malty for me for an American IPA. - Drinking a Koala Blanket @ HopCat - http://t.co/F38TqU6dkz 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.16 0.84] 


Wiz Khalifa look drunk af 
 Original label:  0 Predi

 Probabilities:  [0.63 0.37] 


Guys my brother and his friends are drunk &amp; buying drinks. Send help! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.22 0.78] 


Everybody on my TL drunk I wasn't invited 😔😞 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.47 0.53] 


Now we just gonna drink and chill 😛 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.13 0.87] 


Sometimes you just know when you gotta lay off the drinks 😂✌🏼️ 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.66 0.34] 


I've been everyones drunk call since Thursday foo lmao gah lee 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.51 0.49] 


Haven't been drunk in forever. Goodnight everyone. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.35 0.65] 


I'd Send This Drunk Text But Shawty Would Think I'm Wylin 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.35 0.65] 


When you drunk as h.ll and remember you got Checkers. 😂😩💃🏽 
 Original label:  1 Prediction:  0 

 Original label:  0 Prediction:  1 
 Probabilities:  [0.31 0.69] 


Any basketball records before 1970 should be abolished simply because of lack of talent lol 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


Bday Dranks! (at @230FifthRooftop Lounge in New York, NY) https://t.co/WDFWwjJ59r 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


muzicman424 #Mood #MorningMood #WeddingCountdown #Morning #TGIF #LastNameChangingSoon #AdiosLlaverias… https://t.co/8W0GW44Yu8 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.53 0.47] 


Where to Eat &amp; Drink in Logan Square: http://t.co/XEri6SHovz @yushologan @billysunday @lulacafe @bangbangpie via @michiganavemag 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.39 0.61] 


We thought we'd continue with our coffee beer theme today and sample out @devilstrumpet's Vanilla… https://t.co/P2oHlE5VwU 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.48 0.52] 


2 badass DJs, hot gogo guys, g

 Original label:  0 Prediction:  1 
 Probabilities:  [0.5 0.5] 


Local brewery #2 😋 the pineapple and Hefeweizen were my faves! #santan @ SanTan Brewing Company https://t.co/DdbZsTvXH9 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.6 0.4] 


Ya la escucharon, no se enamoren, no es nada sencillo ver como se aleja tu mayor felicidad. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.54 0.46] 


Omw to my apartment this lady stopped me and started giving me encouraging words 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.31 0.69] 


@thornews ok... is this the same thornews as thornews on youtube?  The crazy drunken texan am astronomer? 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


Check out our #listing in #Chicago #IL http://t.co/ThoKPUg6Si #realestate #realtor http://t.co/zFII5KBEWd 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.6 0.4] 


if anyone wants to go to cedar point Saturday, I have a ticket, a wristband for free dri

 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


No officer, this is just a seltzer can from my office. It's definitely not a seltzer can I emptied and filled with wine from my office. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


So there's this guy from Hanford who accused me of being an alcoholic...lol umn yup sure am one. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


@Jugal_cb35 well I wouldn't let you write it even if you were sober lol 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.75 0.25] 


@EvergreenBeers new pipeworks coming in this week? 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.43 0.57] 


@MulliganFilm @_hoffman 
STOP BY SUNDAY NIGHTS AT ANTRONIO'S 
FOR DRINKS + GREAT CHILL MUSIC W/ DJ LOVE@CHICAGO
https://t.co/mYDwrMevax 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.67 0.33] 


The 40 somethings are rocking and drinking in the rain!! Let's hope nobody ends up in the ER!!☆

 Original label:  0 Prediction:  1 
 Probabilities:  [0.16 0.84] 


@Dude_ImALegend This is a no smoking, no drinking, no fornicating, no point of living at all house! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.44 0.56] 


Don't mind if I do 🍷😋 @ V Wine Room https://t.co/RE28QJcd9a 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


@mark_georgiou @CrookedBeggar @theidealtwit @mommyisaheathen What more is there to say? If person drinks too much, they get Black-Out drunk. 
 Original label:  1 Prediction:  0 
 Probabilities:  [0.62 0.38] 


@SeabournCruise best wine for wine Wednesday, Kitchak cellars Scherzo Cabernet Sauvignon Rosato. Pink wine from Cabernet? #spectacularswine 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.59 0.41] 


Finally back home, my financial advisors have told me that I have surpassed my monthly Beer allowance by a lot.... https://t.co/4OFQO6v3vO 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.46 0.54] 


It's su

 Original label:  0 Prediction:  1 
 Probabilities:  [0.59 0.41] 


Look forward to this release every year!! #craftbeer - Drinking a Saison-Brett (2015) @ Schuman's Pub - http://t.co/RRS537UwJr #photo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.39 0.61] 


@Edgeman_inHD Meat Lovers pizza &amp; Bud Light beer.. (16oz) 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.35 0.65] 


More #Wine for when I #AmWriting http://t.co/KykEjzn6Y7 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


@JPJABBER @utbrp I think he was drunk, dealing with those idiots day in and day out 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.37 0.63] 


Lose money at the casino but get free drinks. Always a winner 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.42 0.58] 


@311 @NickHexum Wedding shout out a huge favor from an Omaha native! Can't wait to see you guys 2x in Vegas and drink some Amber Ale! 
 Original label:  1 Prediction:  0 
 Probabilities:  [

 Original label:  0 Prediction:  1 
 Probabilities:  [0.51 0.49] 


Me: "I am only have 2 7&amp;7's because me and Brian liquor are not a good idea." @madtownb "You got that right. "
#whiskey #schmoozing 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.46 0.54] 


"Let's get drunk" I said, "it'll be fun I said". #diarrhea #diarrhealikeitaintnobodiesbusiness #poop… https://t.co/tyOb7nLHl5 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.5 0.5] 


Great wine with Thai @ Thai Square Restaurant - Devil's Pocket https://t.co/yc1nmkEAlw 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.41 0.59] 


Electric Blue Lemonade #fridaynight #drinks @ Beverly Hills Tavern https://t.co/RfnmS7qZHt 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.44 0.56] 


Starting off the day right w/ a build your own Bloody Mary bar. Later in the day:  some sushi making, whiskey, and anniversary dinner. 7yrs! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


Why do a

 Original label:  0 Prediction:  1 
 Probabilities:  [0.61 0.39] 


She goes great with an ice cold beer, or a shot of whiskey 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.49 0.51] 


When it Rains It Pours....Beers...Midwest Connect...BIG UPS Atom... (Green Diamonds) http://t.co/CvG0jr4QkK #photo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.39 0.61] 


Phone call canceled. . . He's drunk. 
Can't go out. . . My car's in LA. 
Can't watch tv. . . They're watching a movie.
UGHHHH 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.46 0.54] 


@ThomasLS LETZ get a drink this week (vince is invited) 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.5 0.5] 


Just came home to a refrigerator filled with whole foods snacks, beer, and cheese. BEST BOYFRIEND EVER!!! 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.47 0.53] 


I will be with Fred and @zarockthewolf  on this one XD *drunk fox* https://t.co/bL625f5Ee6 
 Original label:  0 Prediction:  1 

 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


No ma'am sorry we don't sell maple syrup at a liquor store... 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


"can we like have wine delivered?" @jeannie1125 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.59 0.41] 


Enjoying a Smithwick's Draught / Premium Irish Ale / Red Ale — http://t.co/qXFlVPEJcm 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.37 0.63] 


@phoenixlokote_ @Gee_hoee wassup you got a plug for some beer rn or nah haha? 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.57 0.43] 


@FaerieGlamour b-b-but Irish whiskey!?! It's the best. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.58 0.42] 


@brosandprose Ella stop drinking it. Omg. Please.

I was a total addict at your age. I think it caused me a lot of pain. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.42 0.58] 


Drink your dinner, boys and girls. #raspberry #margarita @ Sunset Gr

@DonutBrigade No swag yet!! Trying to nail down the whole beer thing first. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.35 0.65] 


@JESSS_playinn I wish I was as drunk as you last night 😂 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.29 0.71] 


Happy birthday @SkinnyCees !! Drink one for me. ☺️🍻 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.12 0.88] 


May not have "lobster and Caviar" money but I do have "large frys and drink" money. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.42 0.58] 


Find all the details for tonight HERE! Head over to @SaintArnold at 7 PM for craft beer, live music and tacos! http://t.co/7tcN9pr1ER 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.6 0.4] 


@ReykaVodka (1) hiking shoes, (2) drinking pants, and (3) a friend to enjoy the beautiful scenery &amp; excellent vodka with :) 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.28 0.72] 


2 drinks and something to hold it down @ Hudson Eatery ht

 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


@disneysquotess ...Drunk Roommates Are Bad Biz -Hahaa 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.53 0.47] 


@jaknowlden, pacify yourself with a drink. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.56 0.44] 


Slow as the Mississippi, strong as a fifth of whiskey 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.58 0.42] 


I'll take all my food and/or drinks to go . Thank you 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.32 0.68] 


Definitely a sour beer but not overly sour which I like. I would... (Technicolor Motorhome) http://t.co/3XrhLFeXAl #photo 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.24 0.76] 


@RayalityCheck We're #notalwaysthirsty. But when we drink, "we like that Do-mestic beer." 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.48 0.52] 


Champagne and pasta and jazz OH MY #cheektocheek @ladygaga @ Joanne Trattoria https://t.co/Vtfu43V2N5

 Probabilities:  [0.54 0.46] 


Clear liquor makes me wanna throw up just looking at it. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.33 0.67] 


When @king_manzo  drinks too much  https://t.co/qvTm6aDu0Q 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.5 0.5] 


Wine night @ Postino's http://t.co/XHwFufCfPO 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.34 0.66] 


Brunch: the socially acceptable excuse to drink before noon ☀️🍹 @ Sunny Spot https://t.co/BxRTX6ESsS 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.49 0.51] 


Jekyll n Hyde... This team makes me drink! https://t.co/8kg4ayMgNp 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.51 0.49] 


@parrillasassyaf LOL I hope not if Lana were drunk, but I'm so happy that she looks so happy be there. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


#🍺 #beer @ The Boardwalk @ Brighton Beach https://t.co/dY2tEQcmCF 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.

 Probabilities:  [0.39 0.61] 


He finna be stupid drunk  https://t.co/WkG1zIma3s 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.46 0.54] 


*and spilling our drinks everywhere while we laugh at Kim's drinking habits (a lot of beer)  https://t.co/teyJkhnnLd 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.51 0.49] 


And he didn't even drink much cause I know he can hang.... then that morning we found he shit on himself all over the walls lol 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.55 0.45] 


Ciroc even though i really dfw drinking  https://t.co/De1mdZv0qR 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.36 0.64] 


@paigieebabiee or we can dress up and get drunk???? 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.41 0.59] 


@n_settle_ no drinking and driving is bad 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.48 0.52] 


@papabreadstick foremost liquor near South Pasadena. 
 Original label:  0 Prediction:  1 
 Probabili

 Probabilities:  [0.48 0.52] 


Boom. (@ World of Beer in Jacksonville, FL w/ @sassyfreshjazz) https://t.co/zojvI6vSnx 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.52 0.48] 


@LargeLocale When you get eaten by I T-Rex I'll pour some vodka out for you as I'm running away. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.43 0.57] 


@angeljordan_yo if we get drunk, we be thinking we look like this.  https://t.co/iSXg35l8SV 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.3 0.7] 


@amyschumer OMG I'm #InsideAmy!  I'm A Little Short On 💸 Can I Borrow Some Vodka?Preferably Not The Vodka You Poured On Your Feet Though! 😂 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.49 0.51] 


@igobyhardy no but when I'm drunk with friends it's good ok😂😂💀 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.17 0.83] 


Coy: did you drink that moonshine? Huntyr: ........." Coy:" that's a question, we answer those." 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂 
 Original label:  0 Predicti

 Probabilities:  [0.61 0.39] 


It's #WineWednesday at #CucinaRustica in #Sedona, AZ. Come enjoy a glass of wine and indulge in some fine Italian. http://t.co/IEZFnAuerG 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.53 0.47] 


I want to leave this doctors office, it's cold, I'm hungry &amp; sober. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.3 0.7] 


@rijgod Sometimes he freestyles tho😭😭 , Bruh gets hella High and drinks hella lean and just gets In the booth fr. 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.37 0.63] 


I want to live in a world where alcohol is zero calories 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.58 0.42] 


Me when I get home drunk :-} jk I don't drink.. https://t.co/fd1XCeNXEr 
 Original label:  0 Prediction:  1 
 Probabilities:  [0.38 0.62] 


@FrozenSoda8 @Allentownmike @shaunholt8587 @ThinkingLWNJ @carlsbadbugkil1 fuck the beergarita -if i wanted a beer w lime, I'd order that 
 Original label:  0 Prediction:  1

It does seem like the classifier is never really sure of the prediction when it disagrees with the original label.

We next create a confusion matrix to get a better sense of where the classifier makes mistakes.

In [20]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(fp_lab, alc_fp_preds, labels=[0,1])
print(conf_mat)

[[1234 2225]
 [ 217 6140]]


It looks like only 217 tweets were mislabeled as not first-person when they were first-person. Compared to the 6140 that were labelled correctly, however, this does not seem like such a big error. What does seem significant is that fewer than half of the tweets originally labeled as not first-person were correctly predicted as such, and 2225 tweets (about 65% of the original not first-person tweets) were incorrectly predicted to be first-person. This might hint at a problem with this level of classifier that we might take a look at later. 

For completeness, we will take a look at the confusion matrix for the alcohol-related classifier that was remarkably accurate above:

In [21]:
conf_mat_alc = confusion_matrix(pred_alc, alc_labels)
print(conf_mat_alc)

[[ 5353     5]
 [    3 10290]]


We can see that this classifier performed about-evenly well classifying alcohol-related vs. not alcohol-related tweets. There were only 8 errors, as we saw before: 3 tweets were misclassified as not alcohol-related and 5 tweets were misclassified as alcohol-related.

We will finally look to see how well the classifier reproduces the first-person-level labels from the original training dataset. 

In [22]:
# appending labels based on whether tweet label contains phrase
fpl_lab = []
fpl_subset_vec = []

fpl = "'first_person_level'"

# extracting FP levels and constructing subset vector simultaneously
for i in range(len(df)):
    if fpl in df.labels[i]:
        fpl_lab.append(int(df.labels[i][df.labels[i].find(fpl) + len(fpl) + 2]))
        fpl_subset_vec.append(1)
    else:
        fpl_subset_vec.append(0)

In [23]:
# running the classifier on the subset we defined above
fpl_idx_vec = list(numpy.where(fpl_subset_vec)[0])
alc_fpl_preds = clf_fpl_dl.predict(df.iloc[fpl_idx_vec,])

In [24]:
# predicting probabilities for FPL for use later
alc_fpl_probs = clf_fpl_dl.predict_proba(df.iloc[fpl_idx_vec,])

In [25]:
fpl_disag = list(map(int, fpl_lab != alc_fpl_preds))
# printing rate of disagreement
sum(fpl_disag)/len(fpl_disag)

0.3312883435582822

We have about 33% disagreement rate. This might seem poor but considering the fact that the classifier only labels up to 3 levels (0, 1, and 2), while the annotated labels had 4 levels (0, 1, 2, 3), this is not so bad. The classifier may not be working properly, however. We will check that now. 

In [26]:
fpl_tweets_disag = df.iloc[fpl_idx_vec,].iloc[list(numpy.where(fpl_disag)[0]),].text
fpl_disag_vec = list(numpy.where(fpl_disag)[0])

for i in fpl_disag_vec:
    print(df.iloc[fpl_idx_vec,].iloc[i,].text, '\n', "Original label: ", fpl_lab[i], "Prediction: ", alc_fpl_preds[i], '\n')

Its only Tuesday and I need a drink or four. 
 Original label:  2 Prediction:  1 

jess told me no puking this friday.. so that means no getting drunk... ouch 😩 
 Original label:  2 Prediction:  0 

I'll be fine just drinking my wine 
 Original label:  2 Prediction:  0 

Wtf was I drinking Sunday?😂🔫🙊 http://t.co/3c2mz1Uz8L 
 Original label:  2 Prediction:  0 

Drinking a Café Deth by @revbrewchicago at @rootspizza — http://t.co/ni9qZl4N9S 
 Original label:  2 Prediction:  0 

In a matter of 10 minutes, whilst trying to be productive, I managed to shatter a wine glass and a bottle of rosé. 😫😫😫 
 Original label:  0 Prediction:  1 

#NoteToSelf Don't drink on a Monday..😣 
 Original label:  2 Prediction:  0 

Whatever Wagner drank, ate, injected before the game needs to be administered again tomorrow. 
 Original label:  0 Prediction:  1 

next stop: sun, sand and a drink in my hand😉🍹 #poet 
 Original label:  0 Prediction:  1 

As much as I'd love to get black out drunk this weekend, I thin

Drinking an 33 by Bubba's 33 @ Bubba's 33 — http://t.co/57X9ZsvuxE 
 Original label:  2 Prediction:  0 

I Rather Be Your N I G G A So We Can Drunk And Smoke Weed All Day. 
 Original label:  2 Prediction:  0 

Females don't get shit sometimes man 😴 
 Original label:  1 Prediction:  2 

Who's tryna drink? 
 Original label:  2 Prediction:  1 

I'm hungover half the time and drunk the  other half 
 Original label:  2 Prediction:  0 

I'm a little drunk on you and height on summertime 🎶 
 Original label:  2 Prediction:  0 

He just drunk a 6oz 🍼 now he sleep!! 👶😴😴 
 Original label:  2 Prediction:  0 

I drink liquor and eat ice cream...Sooooo whatttt 
 Original label:  2 Prediction:  1 

i said i wasn't drinking tonight 
 Original label:  0 Prediction:  1 

I need a public chicken tender sub rn 
 Original label:  0 Prediction:  1 

The only thing to do around here is get drunk and mow your yard 
 Original label:  2 Prediction:  1 

let's eat these noodles, drink these beers and dance our h

 Original label:  0 Prediction:  1 

A little beer and pizza before @Metallica #xgames @XGames http://t.co/MHn5jXooWD 
 Original label:  1 Prediction:  0 

Just got hit on by a drunk middle aged wo(man) at a 21+ club while having dinner with my mom... What is life😂😂 http://t.co/wuvVhIKyCF 
 Original label:  2 Prediction:  0 

I didn't know my night was headed for Coach Keck buying me a bucket of beer &amp; busting out legendary dance moves. Now that's #winning 
 Original label:  0 Prediction:  2 

Omg @AmoHeals just yelled at me "OMG I want a sloppy bottom!"
Laughed so hard I had to go to the floor.

(It's a drink name FYI) 
 Original label:  2 Prediction:  1 

When you're drunk and really want red lobster so you try to look up their hours.... http://t.co/GcERVN4s6S 
 Original label:  2 Prediction:  0 

I just paid $9 for a beer... I hate bars. 
 Original label:  0 Prediction:  1 

Only thing I hate about drinking is having to use the restroom every 15 minutes 😁 
 Original label:  0 Pr

I miss my @LeaBlackMiami I need her #turbans in my life.  When you are in Houston please meet me for a drink #needuinmylife #selfmadebitch 
 Original label:  1 Prediction:  2 

@EvanDonovanNews your welcome love meet up some time chat have a beer local guy grew up mars hill still live mars hill . 
 Original label:  2 Prediction:  1 

Drunk on the beach takes me back 😭😭 
 Original label:  2 Prediction:  0 

Doing research and trying to plan my life out turned into getting drunk with my mom real fast 
 Original label:  2 Prediction:  0 

I drank some wine and now I have pre risky text syndrome. 
 Original label:  0 Prediction:  1 

All I wanna do right now is have peaches and wine in Italy 
 Original label:  2 Prediction:  1 

If it's Molsen Canadian, drink one for me 
 Original label:  2 Prediction:  1 

I be sending drunk texts and be sober af 😂 
 Original label:  0 Prediction:  1 

7. BUT MY DRUNK ASS WAS AGGRESSIVELY AND REPEATEDLY TEXTING HIM BC I WANTED ATTENTION. So he finally tel

Dude stop starin me down...you're drinking Smirnoff ice. 
 Original label:  1 Prediction:  2 

Pours a drink alone w my sick ass garlic and onion meal from out of nowhere, raises it, a toast! to me!!! B) 
 Original label:  0 Prediction:  2 

When you have your first drink all week. Shitz like crack 
 Original label:  1 Prediction:  2 

OITNB with pizza and beer and @Gingerhazing 🙌🙌🙌 
 Original label:  1 Prediction:  0 

Ladies coming through for beer pong 😁 it's lit! 🔥🔥🔥 
 Original label:  0 Prediction:  1 

I pop champagne with who I'm closest too. 
 Original label:  2 Prediction:  0 

I gotta say, it's a bit rough going out &amp; getting drunk, seeing so many cute girls at the bar while being married. Quick fantasies abound! 😍 
 Original label:  2 Prediction:  0 

I just saw my next door neighbor who's a city cop working downtown and I drunkenly spoke more to him tonight then I ever have sober 
 Original label:  2 Prediction:  1 

Drink until you forget what made you drink in the fir

 Original label:  2 Prediction:  0 

Now I'm going to drink beer on my couch and read about the 2005-06 Phoenix Suns. God bless. 
 Original label:  0 Prediction:  1 

Looks like 'drunk me' hid the weed and forgot to leave sober me a note. ...oh, drunk me. 
 Original label:  2 Prediction:  0 

When you're too drunk and brake out your shuffling skills 
 Original label:  1 Prediction:  0 

This vodka is getting better and better as the night goes by😌 
 Original label:  3 Prediction:  0 

dont let drunk ppl have their phone its a train wreck 
 Original label:  2 Prediction:  0 

Annual all white yacht party...had a good night dancing,drinking, laughing...back 2 my reg scheduled… https://t.co/rKFCEBrVUb 
 Original label:  2 Prediction:  0 

Wow serving literally makes me wanna drink so much, it's ridiculous. I put up with so much today &gt;.&gt; 
 Original label:  1 Prediction:  2 

I'm drinkin that bih sideways 💀💀💀 @TyOtf 
 Original label:  3 Prediction:  0 

Lol yaw niggas drunk 😂😂 I woul

When I get drunk. I expect some 🐱 afterwards. 
 Original label:  0 Prediction:  1 

My dad likes to drink beer and hop on the PS4 after work, I see where I get it from... 
 Original label:  2 Prediction:  1 

I smoked a blunt so I can go mimis but it didn't work cause I'm still drunk Lmao fml I have like an hour of sleep left 😬😭😭😭 
 Original label:  0 Prediction:  2 

I am actually unsure if I am still drunk right now or hungover 
 Original label:  2 Prediction:  0 

I Just Wanna Gamble And Get Free Drinks 🍹💰 In AC 
 Original label:  1 Prediction:  0 

Not quite sure if I like seeing my baby drunk... But glad he had a good Graduation Night 😊 
 Original label:  2 Prediction:  0 

It's a good thing I drank that Hennessey earlier. I can't feel shit hummie 
 Original label:  0 Prediction:  2 

Someone come over and hangout. I got alcohol and food 😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊 
 Original label:  0 Prediction:  1 

A year ago today I was sitting at Panama City beach urgent care gettin


2 glasses of wine and 3 episodes of #WaywardPines later 
 Original label:  0 Prediction:  1 

I'm already tipsy let's see how the rest of the night goes. #nyc 
 Original label:  0 Prediction:  2 

2 nights this week I had whiskey on the rocks for dinner. Switching it up tonight with bourbon #merchlife 
 Original label:  2 Prediction:  1 

Drinking a Lowdermilk by @valiantbrewing at @valiantbrewing — http://t.co/S184FWuleN 
 Original label:  2 Prediction:  0 

I didn't get carded for beer rn. I've made it 
 Original label:  0 Prediction:  1 

damn, saw on snapchat @therealjuicyj is in charlotte tonight and is even giving out free beer. should've went!! 
 Original label:  2 Prediction:  0 

I'd rather be drunk on a plane with  Dierks, but LakeShake with Syd was a good second (sorry dan)… https://t.co/ofHYew1HUn 
 Original label:  2 Prediction:  0 

Who really cares when ur drunk 
 Original label:  2 Prediction:  0 

First night I didn't drunk cry in forever #cuzbye 
 Original label:  0 

 Original label:  0 Prediction:  2 

only for the beer and hot dogs #WhoActuallyLikesBaseBall @ Yankee Stadium https://t.co/ipxWnsoCPf 
 Original label:  1 Prediction:  0 

I don't wanna drink and drive let me fall asleep in ya thighs 
 Original label:  0 Prediction:  1 

Frank Zhen goes "you working.. Why every time I see you you have new beer in your hand".. I think I got an addiction http://t.co/VqqglKbqAI 
 Original label:  2 Prediction:  0 

I've been a drunk, I've been a dreamer. Pullin the strings on this ole guitar. 
 Original label:  2 Prediction:  0 

Drinking a Sculpin IPA by @bpbrewing at @kc_branaghans — http://t.co/U5Nq7Lxls3 
 Original label:  2 Prediction:  0 

Got my beer, a nice front porch, and a nicer boy to drink it with 
 Original label:  0 Prediction:  1 

Xan &gt;&gt;&gt;&gt; drinking , smoking 
 Original label:  1 Prediction:  0 

Finally got to drink with my dad! Can't that be a goal??? 
 Original label:  0 Prediction:  1 

me &amp; my mom had a glass of wine 

 Original label:  2 Prediction:  0 

@NORTHTRENTON I did drink #SmirnoffUS long ago. #tempers #temperture #barbarella2015 
 Original label:  2 Prediction:  1 

Not being weird or a bitch at all but lmk before u judge n shove me. The fuck i do to u ? His eyes stray.. Nothing on me. Im jus drinking 
 Original label:  0 Prediction:  2 

I have no old bae's to drunk text or miss lol 
 Original label:  2 Prediction:  0 

Kaitlyn was legit pouring drinks down my throat 
 Original label:  2 Prediction:  1 

I literally always need to have tajin in my beer it's a must! 
 Original label:  0 Prediction:  1 

Everytime I come to walgreens I'm either drunk buying beer or high as fuck buying a shit ton of cAndy 
 Original label:  2 Prediction:  1 

Drinking every night because we drink to my accomplishments 🎶 
 Original label:  2 Prediction:  0 

Gotta open tomorrow and I decided to get drunk. Good job Tyler. 
 Original label:  0 Prediction:  1 

I don't understand how someone could just carelessly

Selfies at the Airport Drinking Wine, Take me Back to Tahoe edition. @ Phoenix Sky Harbor… https://t.co/5ad6uyx3r3 
 Original label:  1 Prediction:  0 

Time for happy hour with the fam aka we have a fridge of beer and twenty bottles of wine 
 Original label:  0 Prediction:  1 

Nothing makes me wanna drink like family gatherings. 
 Original label:  0 Prediction:  1 

Drinking grey goose on a Sunday bc I do what I want 
 Original label:  2 Prediction:  0 

Drinking and chillen with the tio is the best Tbh 😎 
 Original label:  1 Prediction:  0 

Drinking a He'Brew Rejewvenator (2014) by @ShmaltzBrewing @ The Beer Guy's Love Nest — http://t.co/JaRYhgo3Nu 
 Original label:  1 Prediction:  0 

Finished my beer now time for a cold shower👌 
 Original label:  2 Prediction:  1 

Drink on it 🎶 
 Original label:  2 Prediction:  0 

I need more palettes tho 
 Original label:  0 Prediction:  1 

Beer pong @TheHouseHou Is the scene tn 🔥🍻🍻 
 Original label:  2 Prediction:  0 

Hookah, drinks, and bo

 Original label:  2 Prediction:  1 

My bucket list is short.  Making whiskey is in that list.  I don't care about what's popular and I… https://t.co/t6CHCyH9bm 
 Original label:  1 Prediction:  0 

I have 2 coronas and they get me tipsy now! How is that? #light #weight 
 Original label:  1 Prediction:  0 

This sober life is annoying especially when you bored as shit with nothing &amp; noone to chill with 
 Original label:  2 Prediction:  0 

Shower, food, liquor, prayer then sleep 
 Original label:  1 Prediction:  0 

Bring out the champagne aka tequila 😉, join us and celebrate with us tomorrow night at @pub46 for… https://t.co/xcFb950413 
 Original label:  1 Prediction:  0 

@Liquor Proper Way of Making an Old-Fashioned the cognac way for Natl Cognac Day #DrouetCognac http://t.co/sz3BIuZ20H #mixitup42 
 Original label:  2 Prediction:  0 

Just posted a photo @ Napa Valley Wine Country https://t.co/LTfJ5mq2xH 
 Original label:  1 Prediction:  0 

I'm hosting #chickenNbeer this Thursd

Burgers &amp; beer are a perfect pair. Find out who has the best burger this Sunday @PHLburgerbrawl. #PhillyBurgerBrawl http://t.co/gKHENTrO6L 
 Original label:  2 Prediction:  0 

Long week!  Headed for #Afterwork #Cocktails with friends @ Ceres Cafe https://t.co/t6Oo0ahXbF 
 Original label:  1 Prediction:  0 

@southpawluis and I instructing the Midwest how to drink like men. Yeah, I said it! #austinjr http://t.co/eqPWI8vWVq 
 Original label:  3 Prediction:  0 

p.s. 10pm Friday, I am drinking sauvignon blanc, eating frittata and perusing Crate &amp; Barrel stemware, because I'm the whitest person alive. 
 Original label:  1 Prediction:  0 

Hanging with my brother from another mother, Joey Mayo. 😈😊❤️👍🍷🍸🍹🍺 @ Bar 13 https://t.co/M53ikLpJXP 
 Original label:  1 Prediction:  0 

@ABC7Gisela Have my Heisenberg Vodka ordered 
 Original label:  1 Prediction:  0 

Fuck gin lol 
 Original label:  1 Prediction:  0 

#Education #Job alert: Sign Language Interpreter Jobs in San Bernardino | Sol

 Original label:  1 Prediction:  2 

I want to get mad drunk and do crazy shit that I'll definitely regret but it won't matter because I had a great fucking time 
 Original label:  2 Prediction:  1 

Watching Family Guy On Netflix, Eating Ice Cream &amp; Drinking Whiskey 👌 
 Original label:  1 Prediction:  0 

Just downloaded the mini bar app on my phone 😂 I'll be ordering drinks soon! #alcholic 
 Original label:  1 Prediction:  0 

Can't understand how people get hammered weekly... I die now after like 3 beers. Can't believe I used to do it myself. 
 Original label:  2 Prediction:  1 

I leave early and sober she leaves hammered and with her $10 ..... #itsjustdifferent #pt 
 Original label:  2 Prediction:  0 

@libertybells_ I rode BMX there all the time before the skatepark was built. I've shared a beer with scuba steve 
 Original label:  0 Prediction:  2 

@Teekaysue_ lmfao man, I been sober as fuck. like I'm still shaking 🙍🏽 but eating at the same time 😯 
 Original label:  2 Predic

 Original label:  0 Prediction:  1 

That calls for a beer. https://t.co/ntneHbkmcw 
 Original label:  1 Prediction:  0 

@destaneeee__ lol of course 😁 💁🏽 &amp; I have to take a break from alcohol 😩 
 Original label:  2 Prediction:  1 

@TheyScreamTee I might just get drunk af n eat her ass in da hotel 😂😂😂😂 
 Original label:  0 Prediction:  1 

\ monday's just got better \

The best mornings are filled with cookies for breakfast and a drink of… https://t.co/GeS6yJSbAq 
 Original label:  1 Prediction:  0 

"Everyday i spend my time, drinking wine, feeling fine, waiting here to find the sign, i don't care if i never know, here i go" 🎧 
 Original label:  0 Prediction:  2 

@tonyshitdope gucala 😷 I gag every time I drink this lol 
 Original label:  2 Prediction:  0 

I just want to point out, if you saw all those vids lastnight, we were completely sober... Actually 😂 
 Original label:  2 Prediction:  1 

@hitstreak @RiotScarizard maybe it's the alcohol talking but I can't stop laughing at 

 Original label:  2 Prediction:  0 

@ivorypistol22 @Bellla_Amore @goldfish_ninja @CincyWraps @1218artist @loopdlu @gosteelrz dang, wish we could all have a drink together 💜🍻🍷🍸 
 Original label:  0 Prediction:  1 

Yay @livelifejuiced followed me back! Do I get a free drink too?? 😉 
 Original label:  0 Prediction:  1 

A chilled bottle of Rueda after work. @ PIL PIL Spanish Tapas and Wine Bar https://t.co/zLrYlCyEf9 
 Original label:  1 Prediction:  0 

Twitter makes me worry I will eventually hate any future spouse.. So, whiskey? 
 Original label:  1 Prediction:  0 

@lauraaa_veee if it wasn't for you, I'd be running in the forest drunk &amp; pantyless lol 😂😂😂 
 Original label:  0 Prediction:  2 

It's been like 3 weeks since whiskey has touched my lips 😩 
 Original label:  1 Prediction:  0 

@KaviKamil505 shoulda got drunk first https://t.co/pyOPjIj88O 
 Original label:  1 Prediction:  0 

Ever been so hot it makes you not want to drink anymore? Thanks Florida. Lol 
 Original label: 

 Original label:  1 Prediction:  0 

@teenboyjesus @weareadult @sadlilann just cute lil homies hangin out drinkin some brews :-) 
 Original label:  0 Prediction:  1 

@stevencarrier74 Naaaaa get your own vodka 
 Original label:  0 Prediction:  1 

@highvoltage_hpf @856Kcco @cfbfanatic7 @JustinNiehof @KLayAyeee how drunk? 
 Original label:  2 Prediction:  0 

@rob_aden lmao yeah first legal drinks i had at a game made me get all sassy and what not 
 Original label:  0 Prediction:  2 

@ryanmfandrews @mr_oodie_sir so you buying us beer at the lookout right? 
 Original label:  0 Prediction:  2 

I just want some bomb food,  wine, and a foot massage  😄 too much?  lol 
 Original label:  2 Prediction:  1 

@nanagmz08 @not_marissa @kastel_laylonie @anniedannibale @lesliedavis__ and Julianna!! And of course @DoolabhRishi and the boys! 
 Original label:  1 Prediction:  2 

@Body_Em_John lol you never seen me sober for a full 24 hours... 
 Original label:  0 Prediction:  2 

Had a great time w/m


Wine cruise Chicago! #GoldFlakes in the glass. @ Bumham Park Yacht Club https://t.co/jRLnQRGj5a 
 Original label:  2 Prediction:  0 

Ok yea I remember that night lmao. You was so drunk 😂😭 https://t.co/rzjb2l5CZ9 
 Original label:  2 Prediction:  0 

@annaofthewaves @yin00034 @LalaOana Can of beer kicked me to curb😽 
 Original label:  2 Prediction:  1 

@EmersonJJ372 you're going to make drunk Cheryl cry 
 Original label:  0 Prediction:  1 

@ashjstout drunk texting is the worst Hahahahaha I avoid it 
 Original label:  2 Prediction:  0 

🍕 It's #Pizza night! Come by for 2 Pizzas and a pitcher of beer for $25! @ VAN DIEMENS CAFE &amp; BAR https://t.co/HOQHweqbav 
 Original label:  1 Prediction:  0 

Rain makes corn, corn makes whiskey, whiskey makes my baby feel a little frisky 😈😏🎶 
 Original label:  2 Prediction:  0 

The old faithful. Have to get them while I still live in PA... (Philadelphia Pale Ale) http://t.co/MQ0KgnU83g 
 Original label:  1 Prediction:  0 

@ShawnFoxX21 @Godson_

 Original label:  1 Prediction:  2 

@WhiteDoggMike @ManfredandSons I hate dark beer :( 
 Original label:  2 Prediction:  1 

@adame_ just went for drinks and it was great. Heard only good things about brunch 
 Original label:  0 Prediction:  2 

Can't get enough of Napa Valley @ Domaine Carneros Champagne Estate https://t.co/RUNMgi0XyZ 
 Original label:  2 Prediction:  1 

@brianbatten1 @iamshawnrice I agree! Nothing a little beer can’t solve! 
 Original label:  2 Prediction:  1 

Sober up with some tapas &amp; cava. (@ Bom Bolla in Chicago, IL) https://t.co/PCZ61uuBCE 
 Original label:  1 Prediction:  0 

Come cure that @phillybeerweek hangover with me @FieldHousePHL with some @VictoryBeer and @FederalDonuts 2pm! Movies, donuts, couches &amp; beer 
 Original label:  2 Prediction:  1 

Thank God for Klonopin and Gin. #ihateflying #6hourflight #nowboarding 
 Original label:  2 Prediction:  1 

Drinking coffee but wish I was pool side chillin with a mojito 
 Original label:  1 Predictio

 Original label:  0 Prediction:  1 

@Dusanek113 every time I go in there now it literally takes 20mins to get my drink even when it's not busy 😭 
 Original label:  2 Prediction:  1 

..It's that day &amp; hour of the week when "Wings'n Beers" taste oh so good! #HappyFriday 🍻😜 https://t.co/UHmjPR2hz8 
 Original label:  1 Prediction:  0 

We prolly shouldn't be texting, im always forgetin that lesson.I've had one too many to drink and all I can't think is to send u a message 😁 
 Original label:  2 Prediction:  1 

No matter what the situation is, I'm never letting another man pour champagne or any other liquid on me. https://t.co/PIo0kjg1VW 
 Original label:  2 Prediction:  0 

@Justinschillig beer before liquor, ur still getting drunk so don't be a pussy 
 Original label:  0 Prediction:  2 

@ChawlinLately @ketteringpolice he is planing a very large alcohol party tonight with citizens under 21. There also will be meth there. 
 Original label:  2 Prediction:  1 

i want to be a sober si

Jesus Christ when don't I want to get drunk, I'm going to become an alcoholic 
 Original label:  2 Prediction:  1 

*7 am*
"if you &amp; haley are ever drunk somewhere at 2 am and get lost driving, know: odd highways are north &amp; south, &amp; evens are east &amp; west 
 Original label:  1 Prediction:  0 

I'm taking my dad to the game. I told him it's about the beer and quality time with me. 💕 https://t.co/SiFdNIZTEL 
 Original label:  0 Prediction:  1 

Had my annual #rattlesnake roundup party yesterday. The day started with a #bloodymary bar featuring @Titos Vodka http://t.co/OLi84feVC7 
 Original label:  2 Prediction:  0 

time for a drink? #awnaw @ChrisYoungMusic 
 Original label:  2 Prediction:  1 

New ridgewoodwhiskeyassoc!! A group of like minded whiskey enthusiasts that gather in #ridgewood,… https://t.co/Za8JiJUIJq 
 Original label:  1 Prediction:  0 

@Foodiechats @TwoBrothersBeer @LUCKdallas has an AMAZING #coconut beer and this comes from a girl who really isn't a beer 

 Original label:  2 Prediction:  0 

Birthday week has commenced! Flower cred: akcheck (aka best boyfriend ever) Wine cred: myself (of… https://t.co/FxI0WkbCov 
 Original label:  1 Prediction:  0 

.@spyou73 I swear Joseph you are gonna drive me to drink, if you re-gram ONE more time! lol I wanna see ORIGINAL content boo! 
 Original label:  2 Prediction:  1 

@_SaskiaMitchell
Yup &amp; warm!
Love it.
Though I don't drink much.
Only on vacation &amp; s/times @ dinner
Nice after our Waterfront freeze, ay? 
 Original label:  0 Prediction:  2 

Greasy liquor party at my pad who is down 
 Original label:  1 Prediction:  0 

@DaveDTC @winetrain @TravelingWithS we just put some Czech wine on our list! I must say perfect light wines for this weather in NY. 
 Original label:  1 Prediction:  0 

@JesseLopez2150 @romero360luis yes because I smoke and drink lmao 
 Original label:  2 Prediction:  1 

#Champagne &amp; #Cigar Air Jordan Retro 7's 'Championship Pack' coming out tomorrow morning!!… htt

 Original label:  2 Prediction:  0 

@Joycommaashia lol we've never played beer pong? 👀😂😂😂 
 Original label:  2 Prediction:  0 

Hanging at #Cindy for a few drinks afterwork. Nice to have this just two blocks from @BlueMetaIInc… https://t.co/2TkeDyEOAg 
 Original label:  1 Prediction:  0 

Laguardia &amp; American Eagle Airlines are both my absolute least favorite right now. @karmagypsy can I come over for a drink plz? 
 Original label:  0 Prediction:  1 

So sad I can't drink this anymore 😭 http://t.co/3pQg9p0P8U 
 Original label:  2 Prediction:  0 

Super drinkable. Light and just sour enough with some citrus acidity. ... (Berliner Weisse) http://t.co/fHwl6avN7f #photo 
 Original label:  2 Prediction:  0 

#tocamadera Getting ready for this Sunday! We are going all out with the Food &amp; Drinks! #all_shots… https://t.co/Xky7JO63lZ 
 Original label:  1 Prediction:  0 

"It's 9 o'clock on a Saturday. Regular crowd shuffles in. There's an old man sitting next to me, making love to his 

We will now figure out which original labels correspond to the Current, Looking, and Reflecting labels from the paper.

In [27]:
numpy.bincount(fpl_lab)

array([3211, 1676, 1394,   76], dtype=int64)

The "1" and "2" labels correspond to the Looking and Reflecting labels, respectively. However, the Current label seems to have been split between labels "0" and "3." Why this is or whether this split occurred before or after the paper was published we cannot be sure, but the bin counts for these labels (3211 and 76) do add up to what was reported in the paper (3287). 

Next we try to isolate only the tweets that received a label of 3 to see what this label could mean based on the tweet content...

In [28]:
fpl_tweet_3 = df.iloc[fpl_idx_vec,].text[numpy.array(fpl_lab) == 3] # tweets that received "3" label
preds_3 =   alc_fpl_preds[numpy.array(fpl_lab) == 3] # predictions for which tweet received "3" label
fpl_probs_lab3 = numpy.around(alc_fpl_probs[numpy.array(fpl_lab) == 3],2).tolist() # list of probabilities

# printing tweet, original label, prediction, and probabilities
for tweet, pred3, prob in zip(fpl_tweet_3, preds_3, fpl_probs_lab3):
    print(tweet, "\n", "Original first person level: 3  Prediction: ", pred3, "\n", "Probabilities: ", prob, "\n\n")

he straight up drank from my bottle oh my god 
 Original first person level: 3  Prediction:  0 
 Probabilities:  [0.68, 0.06, 0.27] 


Why am I drinking a big cup of straight well gin rn 
 Original first person level: 3  Prediction:  0 
 Probabilities:  [0.98, 0.01, 0.01] 


We he a little horsey named Paul Revere just me and my homies and a quart of beer. 
 Original first person level: 3  Prediction:  0 
 Probabilities:  [0.97, 0.02, 0.01] 


Oh man, my head hurts so bad, I should have saved one beer for the hangover...🍺🔇 
 Original first person level: 3  Prediction:  2 
 Probabilities:  [0.15, 0.14, 0.71] 


ive had more drunk texts and than sober texts today thats cool too 
 Original first person level: 3  Prediction:  2 
 Probabilities:  [0.16, 0.01, 0.83] 


5 am drunk off da whiskey with these two rockstars @officialkukharrell @djanser !!! These guys always... https://t.co/w5In6pjvoU 
 Original first person level: 3  Prediction:  0 
 Probabilities:  [0.99, 0.01, 0.01] 


Sometime

Most of these tweets seemed to receive a "0" label as if the classifier is trying to correctly classify these "3"-labeled tweets, which is good. Looking at accompanying probabilities there does not seem to be a discernible pattern: prediction probability does not seem to be dependent on the label. Finally, it does not seem outwardly apparent what this "3" label would have been for based on the tweet text...

We will finally produce a confusion matrix telling us where exactly the classifier made mistakes.

In [29]:
conf_mat_alc_fpl = confusion_matrix(fpl_lab, alc_fpl_preds)
print(conf_mat_alc_fpl)
print(numpy.bincount(fpl_lab), numpy.bincount(alc_fpl_preds))

[[2538  396  277    0]
 [ 461 1086  129    0]
 [ 517  250  627    0]
 [  44   13   19    0]]
[3211 1676 1394   76] [3560 1745 1052]


In [30]:
print(round(2538/numpy.bincount(alc_fpl_preds)[0],2), 
      round(1086/numpy.bincount(alc_fpl_preds)[1],2),
      round(627/numpy.bincount(alc_fpl_preds)[2],2))

0.71 0.62 0.6


The classifier gets the Current label right about 71% of the time, the Looking label about 62% of the time, and the Reflecting label right about 60% of the time. 

We will try checking some of the probabilities for these tweets to see if they were deemed especially difficult by the classifier to predict a label for. 

In [31]:
alc_fpl_probs = clf_fpl_dl.predict_proba(df.iloc[fpl_idx_vec,])
fpl_probs_lab3 = numpy.around(alc_fpl_probs[numpy.array(fpl_lab) == 3],2).tolist()


In [32]:
fpl_probs_lab3 = numpy.around(alc_fpl_probs[numpy.array(fpl_lab) == 3],2).tolist()


-------------------------------------------------------
-----------------------

Yijun:

In [81]:
df.head()

_id                      created_at  \
0  556e0ee3d6dfbb462880f0a5  Tue Jun 02 20:16:08 +0000 2015   
1  556e128ad6dfbb46288111e4  Tue Jun 02 20:31:44 +0000 2015   
2  556e12e6d6dfbb462881153e  Tue Jun 02 20:33:15 +0000 2015   
3  556e1464d6dfbb4628812330  Tue Jun 02 20:39:37 +0000 2015   
4  556e15f1d6dfbb4628813236  Tue Jun 02 20:46:14 +0000 2015   

                                              labels   predict  \
0                                     {'alcohol': 0}  0.526050   
1  {'alcohol': 1, 'first_person': 0, 'alcohol_rel...  0.516649   
2  {'alcohol': 1, 'first_person_level': 0, 'first...  0.523513   
3  {'alcohol': 1, 'first_person': 0, 'alcohol_rel...  0.502633   
4  {'alcohol': 1, 'first_person': 0, 'alcohol_rel...  0.535758   

                                                text  \
0  Impatiently waiting to get our hands on the ne...   
1  Beer fans need their @ColumbusBrewing Bodhi. I...   
2  Beer Olympics with my #1 fan and babe😍❤️ #Team...   
3  Stone Cold use to be the baddest MF in my book...   
4  Now @iamjohnoliver has to drink a Bud Light Li...   

                                                user  \
0  {'created_at': 'Thu Jun 12 22:14:05 +0000 2014...   
1  {'created_at': 'Mon Oct 06 21:00:38 +0000 2008...   
2  {'created_at': 'Tue Dec 20 02:46:19 +0000 2011...   
3  {'created_at': 'Sun Mar 11 08:22:56 +0000 2012...   
4  {'created_at': 'Thu Jan 14 03:03:33 +0000 2010...   

                  user.created_at user.favourites_count  user.followers_count  \
0  Thu Jun 12 22:14:05 +0000 2014                   394                 407.0   
1  Mon Oct 06 21:00:38 +0000 2008                   806                1006.0   
2  Tue Dec 20 02:46:19 +0000 2011                 11662                 563.0   
3  Sun Mar 11 08:22:56 +0000 2012                   860                 703.0   
4  Thu Jan 14 03:03:33 +0000 2010                  3473                9414.0   

   user.friends_count  user.statuses_count user.verified  
0              1997.0                823.0         False  
1               960.0              10442.0         False  
2               356.0              13940.0         False  
3               684.0              89573.0         False  
4              1486.0              16435.0          True

In [98]:
# split data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, df.labels, test_size=0.1, random_state=26)

In [99]:
# print(X_train[:5])
# X_train[:5]
# X_test[:5]
y_train[:5]
y_test[:5]
print('training set:', len(X_train))
print('testing set:', len(X_test))


training set: 14085
testing set: 1566


------------------------
This section is for code that may be used later...

In [33]:
#preds = clf_alc

#preds = clf_fpt.predict(pd_test)
#print(preds)

#for tweet, prediction in zip(tweets, preds):
#    print(tweet, '\n',prediction, '\n \n')

from operator import eq

list1 = [1,2,3] 
list2 = [4,5,6]

list(map(eq, list1, list2))

[False, False, False]

In [34]:
x = clf_alc.named_steps["clf"]
y = clf_alc.named_steps['features']

In [35]:
x.coef_

array([[-2.53405597,  0.87940841,  5.56477366, ..., -3.24180786,
        -1.35429585,  2.02874986]])

In [36]:
# trying to extract labels here
fpl_lab = []

fpl = "'first_person_level'"

# extracting FP levels
for i in range(len(df)):
    if fpl in df.labels[i]:
        fpl_lab.append(int(df.labels[i][df.labels[i].find(fpl) + len(fpl) + 2]))
    else:
        fpl_lab.append(-1) # adding -1 here to mark where no label was given
        
# subsetting to run the classifier only on tweets that received a FPL label originally
fpl_subset_vec = []

for i in range(len(fpl_lab)):
    if fpl_lab[i] != -1:
        fpl_subset_vec.append(1)
    else:
        fpl_subset_vec.append(0)

In [37]:
# getting index for disagreement tweets (FPL)
fpl_idx_disag = df.iloc[fpl_idx_vec,].iloc[list(numpy.where(fpl_disag)[0]),].index.tolist()

In [38]:
#print(fp_lab[0:10], alc_fp_preds[0:10], disag[0:10])
#print(df.iloc[subset_vector,].text)
#for x,y,z in zip(subset_vector, fp_lab, alc_fp_preds): 
#    print(df.iloc[x].text)
#    print("Label: ", y, " -- prediction: ", z)
#    print("Agreement: ", y == z)
#    print("\n\n")


#for x,y,z in zip(disag, fp_lab, alc_fp_preds): 
#    print(df.iloc[x].text)
#    print("Label: ", y, " -- prediction: ", z)
#    print("Agreement: ", y == z)
#    print("\n\n")
